// The third-party notices file (ADR 0006 decision 5): plain text, one section per npm package,
// then the components compiled into them and the fonts, each with the version shipped and the full
// license texts. Sorted and free of dates, so the same tree always gives the same bytes.

import type { Collected, TextFile } from './collect.ts';

/** The file's name, at the root of each build. */
export const NOTICES_FILE = 'third-party-notices.txt';

const RULE = '='.repeat(78);
const THIN = '-'.repeat(78);

function texts(files: readonly TextFile[]): string[] {
  return files
    .filter((f): f is TextFile & { text: string } => f.text !== null)
    .flatMap((f) => [`--- ${f.name} ---`, '', f.text, '']);
}

interface Section {
  title: string;
  fields: [string, string | null][];
  body: string[];
}

function section(s: Section): string[] {
  return [
    RULE,
    s.title,
    ...s.fields.filter(([, v]) => v).map(([k, v]) => `${k}: ${v}`),
    THIN,
    '',
    ...s.body,
  ];
}

/** `1 font`, `2 fonts`. */
export function count(n: number, noun: string): string {
  return `${n} ${noun}${n === 1 ? '' : 's'}`;
}

export function renderNotices(collected: Collected): string {
  const { target } = collected;
  const components = collected.manual.filter((m) => m.entry.kind === 'component');
  const fonts = collected.manual.filter((m) => m.entry.kind === 'font');
  const shipped = new Set(collected.packages.map((p) => p.name));

  const toc = [
    ...collected.packages.map((p) => `  ${p.name} ${p.version} (${p.license ?? 'no license'})`),
    ...collected.manual.map((m) => `  ${m.entry.name}, ${m.entry.version} (${m.entry.license})`),
  ];

  const lines: string[] = [
    `Third-party notices: manufakture, ${target.title}`,
    '',
    'manufakture is free software, licensed under the GNU General Public License, version 3 or',
    '(at your option) any later version (GPL-3.0-or-later). This file lists the third-party',
    'software this build ships, with the version shipped and the full text of each license and',
    'NOTICE file. The rules for what may ship are in docs/adr/0006-licensing.md; the WebAssembly',
    'modules and where their source is are named on source.html in the web app.',
    '',
    'Generated by tools/licenses from the installed packages; do not edit by hand.',
    '',
    `Contents (${count(collected.packages.length, 'npm package')}, ${count(components.length, 'component')} inside them, ${count(fonts.length, 'font')}):`,
    '',
    ...toc,
    '',
  ];

  for (const p of collected.packages) {
    lines.push(
      ...section({
        title: `${p.name} ${p.version}`,
        fields: [
          ['License', p.license],
          ['Source', p.repository],
          ['Note', p.manualNote],
        ],
        body: [...texts(p.licenseFiles), ...texts(p.manualTexts), ...texts(p.noticeFiles)],
      }),
    );
  }

  for (const { entry, texts: files } of [...components, ...fonts]) {
    const inside = entry.inside.filter((p) => shipped.has(p));
    lines.push(
      ...section({
        title: `${entry.name}, ${entry.version}`,
        fields: [
          ['License', entry.license],
          ['Source', entry.source],
          ['Inside', inside.length ? inside.join(', ') : null],
          ['Files', entry.files?.map((f) => f.path.split('/').pop()).join(', ') ?? null],
          ['Note', entry.note],
        ],
        body: texts(files),
      }),
    );
  }

  return lines.join('\n').replace(/\n+$/, '') + '\n';
}
