// Built-in motor entries (T9.2b; ADR 0017 decisions 7 and 8; T9.0c's representative parts).
// Typical published values, every one `verified: false`: none has been checked against the maker's
// current datasheet. Each states the convention of its Kv, Kt, R and L as the source gives it;
// where the source does not say, the convention chosen is marked `estimated` and the notes say
// why. Ratings are SI (rad/s, N*m, A, ohm, H, K), dimensions millimetres, mass kilograms.
// Nothing here says a motor is fit for a design: the checks state margins, not approval.

import type { BuiltinEntry } from '../parts/catalog';

const READ = '2026-10-10';
const rpm = (v: number) => (v * 2 * Math.PI) / 60;
/** Kv in rpm/V to SI (rad/s per volt). */
const kvRpm = rpm;
const degC = (v: number) => v + 273.15;
/** g*cm^2 to kg*m^2. */
const gcm2 = (v: number) => v * 1e-7;

const ODRIVE_MOTORS = {
  title:
    'ODrive documentation, ODrive motors (voltages line-to-line amplitude, currents phase amplitude)',
  url: 'https://docs.odriverobotics.com/v/latest/hardware/odrive-motors.html',
  revision: 'docs "latest"',
  read: READ,
};

const ODRIVE_NOTE =
  'ODrive states that all its voltages are line-to-line amplitude and all its currents phase amplitude. Kt is 8.27 / Kv to the published digits. Rated and peak torque are Kt times the current, estimated here. Thermal data, rotor inertia and mass were not on the page.';

/** The built-in motors, every version. */
export const MOTOR_ENTRIES: readonly BuiltinEntry[] = [
  {
    id: 'motor/cubemars-ak80-9-v3-kv100',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'CubeMars',
    partNumber: 'AK80-9 V3.0 KV100',
    description: 'Robotic actuator: outrunner with a 9:1 planetary reduction, delta winding',
    ratings: {
      kind: { text: 'geared actuator' },
      winding: { text: 'delta' },
      kv: { value: kvRpm(100), convention: 'line-to-line amplitude', estimated: true },
      kt: { value: 0.095, convention: 'phase amplitude', estimated: true },
      resistance: { value: 0.16, convention: 'line-to-line' },
      inductance: { value: 116e-6, convention: 'line-to-line' },
      polePairs: { value: 21 },
      ratedCurrent: { value: 12, basis: 'rated, at 48 V; cooling not stated' },
      peakCurrent: { value: 28, basis: 'peak; duration not stated' },
      ratedTorque: { value: 9, basis: 'at the output, at 12 A' },
      peakTorque: { value: 22, basis: 'at the output, at 28 A' },
      noLoadSpeed: { value: rpm(570), basis: 'at the output, at 48 V' },
      ratedSpeed: { value: rpm(390) },
      rotorInertia: { value: gcm2(1118.3238) },
      ratio: { value: 9 },
      gearEfficiency: { value: 0.88, estimated: true },
      backlash: { value: 15 },
      thermalResistance: { unknown: true },
      thermalTimeConstant: { unknown: true },
      maxWindingTemperature: { unknown: true },
      sensors: { text: 'single magnetic encoder, 16 bit; NTC thermistor' },
    },
    dimensions: { diameter: { value: 98 }, length: { value: 38.5 } },
    mass: { value: 0.49 },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [
      {
        title: 'CubeMars, AK80-9 V3.0 robotic actuator product page',
        url: 'https://www.cubemars.com/product/ak80-9-v3-0-robotic-actuator.html',
        read: READ,
      },
    ],
    verified: false,
    notes:
      'Resistance and inductance are published phase to phase, delta winding. The page does not say which Kv and Kt definitions or which side it uses: Kv 100 at 48 V gives 533 rpm at the output against 570 published, which reads as motor side (T9.0c), so both are entered as motor side, line-to-line amplitude and phase amplitude, marked estimated. Kt 0.095 does not equal 8.27 / Kv (0.083). Gear efficiency 0.88 is estimated from 9 N*m / 12 A against 0.095 x 9. Insulation class C; no winding temperature limit stated. Rotor inertia is the motor rotor before the reduction.',
  },
  {
    id: 'motor/cubemars-ro100-kv55',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'CubeMars',
    partNumber: 'RO100 KV55 (standard, with Hall)',
    description: 'Frameless outrunner torque motor, 113.5 mm diameter, star winding',
    ratings: {
      kind: { text: 'frameless' },
      winding: { text: 'wye' },
      kv: { value: kvRpm(55), convention: 'line-to-line amplitude', estimated: true },
      kt: { value: 0.2, convention: 'dc (six-step)', estimated: true },
      resistance: { value: 0.143, convention: 'line-to-line' },
      inductance: { value: 137e-6, convention: 'line-to-line' },
      polePairs: { value: 21 },
      ratedCurrent: { value: 20, basis: 'rated, "A DC", at 48 V; cooling not stated' },
      peakCurrent: { value: 62, basis: 'peak, "A DC"; duration not stated' },
      ratedTorque: { value: 4, basis: 'rated, at 20 A' },
      peakTorque: { value: 12, basis: 'peak, at 62 A' },
      noLoadSpeed: { value: rpm(2550), basis: 'at 48 V' },
      ratedSpeed: { value: rpm(2000) },
      rotorInertia: { value: gcm2(8700) },
      cogging: { value: 0.055 },
      thermalResistance: { unknown: true },
      thermalTimeConstant: { unknown: true },
      maxWindingTemperature: { value: degC(155), estimated: true },
      sensors: { text: 'Hall sensors; temperature sensor' },
    },
    dimensions: { diameter: { value: 113.5 }, length: { value: 36.2 } },
    mass: { value: 0.71 },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [
      {
        title:
          'CubeMars, RO100 KV55 frameless torque motor product page (read through a summarising fetch)',
        url: 'https://www.cubemars.com/product/ro100-kv55-standard-with-hall-frameless-torque-motor.html',
        read: READ,
      },
    ],
    verified: false,
    notes:
      'The large flat torque motor class a direct-drive or lightly reduced cable trainer would use. Resistance and inductance are published phase to phase. The page does not name its Kt definition; its currents are "A DC" and its Km of 0.53 N*m/sqrt(W) equals 0.2 / sqrt(0.143), the DC (six-step) motor constant, so Kt is entered as dc (six-step), estimated. Kt and Kv do not agree under any listed convention (Kv 55, stored as line-to-line amplitude, gives 0.150 phase amplitude, a DC equivalent of 0.166, against the published 0.2), so check both against the maker. Ke 18.67 V/krpm is also published. The winding limit is the insulation class F rating (155 degC), estimated; the operating range is -20 to 50 degC.',
  },
  {
    id: 'motor/maxon-ec90-flat-323772',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'maxon motor',
    partNumber: 'EC 90 flat 323772 (24 V, with Hall sensors)',
    description: 'Brushless flat outrunner, 90 mm, 90 W, block commutated',
    ratings: {
      kind: { text: 'outrunner' },
      kv: { value: kvRpm(135), convention: 'dc (six-step)' },
      kt: { value: 0.0705, convention: 'dc (six-step)' },
      resistance: { value: 0.363, convention: 'line-to-line' },
      inductance: { value: 0.264e-3, convention: 'line-to-line' },
      polePairs: { value: 12 },
      ratedCurrent: {
        value: 5.39,
        basis: 'nominal (maximum continuous) current at 24 V, 25 degC ambient, maxon test mounting',
      },
      ratedTorque: { value: 0.387, basis: 'nominal (maximum continuous) torque, as the current' },
      noLoadSpeed: { value: rpm(3190), basis: 'at 24 V' },
      noLoadCurrent: { value: 0.539, basis: 'at 24 V and 3190 rpm' },
      ratedSpeed: { value: rpm(2650) },
      rotorInertia: { value: gcm2(3060) },
      thermalResistance: {
        value: 4.88,
        basis: 'winding to housing 2.99 K/W plus housing to ambient 1.89 K/W, maxon test mounting',
      },
      windingHousingResistance: { value: 2.99 },
      thermalTimeConstant: { value: 52.6 },
      housingTimeConstant: { value: 281 },
      maxWindingTemperature: { value: degC(125) },
      sensors: { text: 'Hall sensors' },
    },
    dimensions: { diameter: { value: 90 } },
    mass: { value: 0.648 },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [
      {
        title: 'maxon EC motor catalog, EC 90 flat, page 197 ("Motor Data (provisional)")',
        url: 'https://mat.transtechnik.fr/LINMOT/documentation/Moteurs/EC%20Motors/Maxon/Maxon%20-%20EC_90_flat_244879.pdf',
        revision: 'April 2006 edition',
        read: READ,
      },
    ],
    verified: false,
    notes:
      'A DC-equivalent rating of a block-commutated motor: terminal resistance and inductance phase to phase, DC torque and speed constants (their product is 30000 / pi to 0.3 %). The one motor here with published thermal data; T9.0b fitted its model to this sheet. Later editions list other nominal values for this winding (444 mN*m, 6.06 A), so the edition matters. Maximum permissible speed 5000 rpm; ambient -40 to +100 degC. Stall torque 4.67 N*m is a characteristic, not a rating.',
  },
  {
    id: 'motor/mjbots-mj5208',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'mjbots',
    partNumber: 'mj5208',
    description: 'Gimbal-style outrunner, 63 mm diameter',
    ratings: {
      kind: { text: 'outrunner' },
      kv: { value: kvRpm(330), convention: 'line-to-line amplitude', estimated: true },
      resistance: { value: 0.047, convention: 'phase-neutral', estimated: true },
      peakTorque: { value: 1.7, basis: 'peak; current and duration not stated' },
      thermalResistance: { unknown: true },
      maxWindingTemperature: { unknown: true },
    },
    dimensions: { diameter: { value: 63 }, length: { value: 25 } },
    mass: { value: 0.193 },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [
      {
        title: 'mjbots, mj5208 product page',
        url: 'https://mjbots.com/products/mj5208',
        read: READ,
      },
      {
        title: 'mjbots blog, "Representing torque constant as Kv in moteus"',
        url: 'https://blog.mjbots.com/2025/04/17/representing-torque-constant-as-kv-in-moteus/',
        revision: '2025-04-17',
        read: READ,
      },
    ],
    verified: false,
    notes:
      'Mass with wires. Maximum speed 7500 rpm and peak power 600 W are also published. The resistance, 0.047 ohm "line to center" (phase to neutral), came from a search summary, not the current page, so it is marked estimated. Since firmware 2025-03-27 mjbots defines Kv by the peak-to-peak voltage between two phases; whether the page predates that is not stated, so the Kv convention is a guess (estimated), and a peak-to-peak reading would double the amplitude Kv. No Kt is given: the app derives it from Kv.',
  },
  {
    id: 'motor/odrive-botwheel',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'ODrive Robotics',
    partNumber: 'Botwheel',
    description: 'Hub motor with integrated Hall sensors and incremental encoder',
    ratings: {
      kind: { text: 'hub' },
      kv: { value: kvRpm(8.7), convention: 'line-to-line amplitude' },
      kt: { value: 0.951, convention: 'phase amplitude' },
      resistance: { value: 0.8, convention: 'phase-neutral' },
      inductance: { value: 1.7e-3, convention: 'phase-neutral' },
      polePairs: { value: 15 },
      ratedCurrent: { value: 5, basis: 'continuous, phase amplitude; cooling not stated' },
      peakCurrent: { value: 15, basis: '3 s, phase amplitude' },
      ratedTorque: { value: 4.8, estimated: true, basis: 'Kt x 5 A, estimated' },
      peakTorque: { value: 14, estimated: true, basis: 'Kt x 15 A, 3 s, estimated' },
      thermalResistance: { unknown: true },
      thermalTimeConstant: { unknown: true },
      maxWindingTemperature: { unknown: true },
      rotorInertia: { unknown: true },
      sensors: { text: 'Hall sensors; 3200 CPR incremental encoder; NTC 20k 3950' },
    },
    mass: { unknown: true },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [ODRIVE_MOTORS],
    verified: false,
    notes: ODRIVE_NOTE,
  },
  {
    id: 'motor/odrive-d5065-270kv',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'ODrive Robotics',
    partNumber: 'D5065 270KV',
    description: 'Outrunner, 50 mm class',
    ratings: {
      kind: { text: 'outrunner' },
      kv: { value: kvRpm(270), convention: 'line-to-line amplitude' },
      kt: { value: 0.031, convention: 'phase amplitude' },
      resistance: { value: 0.039, convention: 'phase-neutral' },
      inductance: { value: 16e-6, convention: 'phase-neutral' },
      polePairs: { value: 7 },
      ratedCurrent: { value: 45, basis: 'continuous, free air, phase amplitude (65 A forced air)' },
      peakCurrent: { value: 85, basis: '3 s, phase amplitude' },
      ratedTorque: { value: 1.4, estimated: true, basis: 'Kt x 45 A free air, estimated' },
      peakTorque: { value: 2.6, estimated: true, basis: 'Kt x 85 A, 3 s, estimated' },
      thermalResistance: { unknown: true },
      thermalTimeConstant: { unknown: true },
      maxWindingTemperature: { unknown: true },
      rotorInertia: { unknown: true },
      sensors: { text: 'NTC 10k 3435' },
    },
    mass: { unknown: true },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [ODRIVE_MOTORS],
    verified: false,
    notes: ODRIVE_NOTE,
  },
  {
    id: 'motor/odrive-d6374-150kv',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'ODrive Robotics',
    partNumber: 'D6374 150KV',
    description: 'Outrunner, 63 mm class',
    ratings: {
      kind: { text: 'outrunner' },
      kv: { value: kvRpm(150), convention: 'line-to-line amplitude' },
      kt: { value: 0.055, convention: 'phase amplitude' },
      resistance: { value: 0.039, convention: 'phase-neutral' },
      inductance: { value: 24e-6, convention: 'phase-neutral' },
      polePairs: { value: 7 },
      ratedCurrent: { value: 50, basis: 'continuous, free air, phase amplitude (70 A forced air)' },
      peakCurrent: { value: 90, basis: '3 s, phase amplitude' },
      ratedTorque: { value: 2.75, estimated: true, basis: 'Kt x 50 A free air, estimated' },
      peakTorque: { value: 4.95, estimated: true, basis: 'Kt x 90 A, 3 s, estimated' },
      thermalResistance: { unknown: true },
      thermalTimeConstant: { unknown: true },
      maxWindingTemperature: { unknown: true },
      rotorInertia: { unknown: true },
      sensors: { text: 'NTC 10k 3435' },
    },
    mass: { unknown: true },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [ODRIVE_MOTORS],
    verified: false,
    notes: ODRIVE_NOTE,
  },
  {
    id: 'motor/odrive-m8325s-100kv',
    version: 1,
    family: 'motor',
    fieldsVersion: 2,
    maker: 'ODrive Robotics',
    partNumber: 'M8325s 100KV',
    description: 'Wide outrunner, 83 mm class',
    ratings: {
      kind: { text: 'outrunner' },
      kv: { value: kvRpm(100), convention: 'line-to-line amplitude' },
      kt: { value: 0.083, convention: 'phase amplitude' },
      resistance: { value: 0.024, convention: 'phase-neutral' },
      inductance: { value: 9.9e-6, convention: 'phase-neutral' },
      polePairs: { value: 20 },
      ratedCurrent: { value: 40, basis: 'continuous, free air, phase amplitude (60 A forced air)' },
      peakCurrent: { value: 80, basis: '3 s, phase amplitude' },
      ratedTorque: { value: 3.3, estimated: true, basis: 'Kt x 40 A free air, estimated' },
      peakTorque: { value: 6.6, estimated: true, basis: 'Kt x 80 A, 3 s, estimated' },
      thermalResistance: { unknown: true },
      thermalTimeConstant: { unknown: true },
      maxWindingTemperature: { unknown: true },
      rotorInertia: { unknown: true },
      sensors: { text: 'NTC 10k 3435' },
    },
    mass: { unknown: true },
    geometry: { kind: 'placeholder', shape: { kind: 'cylinder' } },
    sources: [ODRIVE_MOTORS],
    verified: false,
    notes: ODRIVE_NOTE,
  },
];
