export const packageName = '@manufakture/nesting';

export { EPS, type Progress, type Unplaced, type UnplacedReason } from './common';
export {
  CHOICE_RULES,
  SHEET_SORT_RULES,
  SPLIT_RULES,
  cutSequence,
  layoutSheets,
  layoutSheetsAsync,
  layoutSheetsSteps,
  orientations,
  resolveMaxStages,
  resolveTrims,
  usableRect,
  type Axis,
  type ChoiceRule,
  type CutTree,
  type CutTreeCut,
  type CutTreeLeftover,
  type CutTreePart,
  type Grain,
  type Placement,
  type Rect,
  type SheetCut,
  type SheetInput,
  type SheetLayout,
  type SheetLayoutResult,
  type SheetPart,
  type SheetRule,
  type SheetSettings,
  type SheetSortRule,
  type SheetStock,
  type SheetTrims,
  type SplitRule,
  type StockOrder,
  type StockUsage,
} from './sheet';
export { checkSheetLayout } from './sheet-check';
export {
  FIT_RULES,
  STICK_SORT_RULES,
  STICK_STOCK_ORDERS,
  checkStickLayout,
  layoutSticks,
  layoutSticksAsync,
  layoutSticksSteps,
  resolveStickTrims,
  type FitRule,
  type StickCut,
  type StickInput,
  type StickLayout,
  type StickLayoutResult,
  type StickPart,
  type StickRule,
  type StickSettings,
  type StickSortRule,
  type StickStock,
  type StickStockOrder,
} from './stick';
