export const packageName = '@manufakture/assembly';

export type {
  AssemblyInput,
  AssemblyIssue,
  AssemblyWarning,
  ConnectorInput,
  DragReport,
  DragTarget,
  InstanceInput,
  IssueCode,
  MateGroup,
  MateInput,
  MateKind,
  MateLimits,
  MateReport,
  MateStatus,
  Outcome,
  Residual,
  SolveReport,
} from './model';
export {
  MATE_KINDS,
  clampToLimits,
  coordinateAxes,
  coordinateCount,
  coordinateNames,
  frameAxes,
  hasLimits,
  isAngular,
  limitViolation,
  type FrameAxes,
  type LimitViolation,
} from './mates';
export { drag, solve } from './solver';
export {
  MAX_SWEEP_VALUES,
  posedMate,
  solveAtCoordinate,
  sweepValues,
  type CoordinateSolve,
  type PosedMate,
} from './sweep';
export {
  IDENTITY,
  compose,
  exp,
  invert,
  log,
  pose,
  quatFromAxisAngle,
  quatFromRotationVector,
  rotateVector,
  rotationVector,
  transformPoint,
  type Pose,
  type Quat,
  type Twist,
  type Vec3,
} from './transform';
