export const packageName = '@manufakture/core';

export * from './schema';
export * from './result';
export * from './ids';
export * from './features';
export * from './document';
export * from './display';
export {
  MATERIALS,
  MATERIAL_IDS,
  MATERIAL_PROPERTIES,
  PRINTED_KNOCKDOWN_START,
  USER_MATERIAL_ID_PATTERN,
  findMaterial,
  massGrams,
  type FatigueCurve,
  type FatiguePoint,
  type Material,
  type MaterialCategory,
  type MaterialDef,
  type MaterialDefProperty,
  type MaterialForm,
  type MaterialId,
  type MaterialProperties,
  type MaterialPropertyInfo,
  type MaterialPropertyKey,
  type Property,
} from './materials';
export {
  bodyCreationProblem,
  checkDocument,
  expressionMeasures,
  expressionReferences,
  expressionVariableNames,
  measuresModel,
  validateDocument,
  variableOrder,
} from './validate';
export {
  CommandSchema,
  MAX_ASSEMBLY_NAME,
  MAX_CAM_SETUP_NAME,
  MAX_DOCUMENT_NAME,
  MAX_DRAWING_NAME,
  MAX_PART_NAME,
  MAX_PRINT_SETUP_NAME,
  PART_ID_PATTERN,
  SimpleCommandSchema,
  applyCommand,
  assemblyViews,
  explodedViewViews,
  fontUsers,
  instanceDimensions,
  partCamSetups,
  partInstances,
  partParameters,
  partPrintItems,
  partViews,
  restoredDocument,
  rowInstances,
  scriptUsers,
  variableCamUsers,
  variableDrawings,
  variableExplodedViews,
  variableMates,
  variableParameters,
  variablePrintSetups,
  variableUsers,
  type Applied,
  type BatchCommand,
  type Command,
  type CommandType,
  type SimpleCommand,
} from './commands';
export {
  camVariableUses,
  drawingVariableUses,
  inlineVariable,
  measuredVariables,
  measurementKey,
  measurementLookup,
  renameVariable,
  rewriteReferences,
  splitMeasuredFace,
  variableUses,
  type CamVariableUse,
  type DrawingVariableUse,
  type MeasuredFace,
  type Measurement,
  type VariableUse,
} from './variables';
export {
  applyConfigurationRow,
  configurationRow,
  configured,
  configuredVariables,
  emptyConfigurations,
} from './configurations';
export {
  diffDocuments,
  type AssemblyChange,
  type CamChange,
  type DocumentChange,
  type DrawingsChange,
  type ItemChanges,
  type PartChange,
  type PrintChange,
} from './changes';
export {
  DocumentStore,
  type ChangeCause,
  type ChangeEvent,
  type ChangeListener,
  type HistoryEntry,
  type StoreOptions,
} from './store';
export {
  COMMAND_MIGRATIONS,
  FORMAT_MIGRATIONS,
  NAMING_MIGRATIONS,
  migrateCommand,
  migrateV0ToV1,
  migrateV1ToV2,
  migrateV2ToV3,
  migrateV3ToV4,
  migrateV4ToV5,
  migrateV5ToV6,
  migrateV6ToV7,
  migrateV7ToV8,
  migrateV8ToV9,
  migrateV9ToV10,
  migrateV10ToV11,
  migrateV11ToV12,
  migrateV12ToV13,
  migrateV13ToV14,
  type CommandMigration,
  type CommandMigrationOptions,
  type JsonObject,
  type Migration,
} from './migrations';
export {
  deserialize,
  migrateJson,
  parseDocument,
  serialize,
  type Loaded,
  type MigrationOptions,
} from './format';
export {
  compareNames,
  mapName,
  parseName,
  printName,
  subIdsInName,
  type NameMaps,
  type NamePart,
} from './names';
export {
  COUNTER_SCOPES,
  CAM_SCOPE,
  DOCUMENT_SCOPE,
  PRINT_SCOPE,
  assemblyScope,
  counterRegressions,
  documentCounters,
  drawingScope,
  idCounter,
  idText,
  maxCounters,
  nextNumber,
  partScope,
  type CounterRegression,
  type CounterScopeKind,
  type CounterTable,
  type ScopeKey,
} from './scopes';
export {
  TOMBSTONE_FIELD,
  commandIds,
  createdFeatures,
  emptyRemapReport,
  isValidRename,
  remapDocument,
  remapIds,
  tombstoneId,
  type RemapOptions,
  type RemapReport,
  type RemapResolver,
  type RenameTable,
} from './remap';
export {
  CreatedIdsSchema,
  MAX_CREATED_IDS,
  PROTOCOL_VERSION,
  RenameTableSchema,
  SyncEntrySchema,
  createdIds,
  freshRenames,
  remapCreatedIds,
  remapScopeKey,
  takenIds,
  tombstoneTable,
  type CreatedIds,
  type FreshRenamesOptions,
  type SyncEntry,
} from './sync';
