export const packageName = '@manufakture/units';

export type {
  BinaryNode,
  BinaryOperator,
  CallNode,
  Expression,
  MeasureNode,
  NumberNode,
  PercentNode,
  PitchNode,
  StringNode,
  UnaryNode,
  UnitNode,
  VariableNode,
} from './ast';
export {
  ANGLE,
  CURRENT,
  DIMENSIONLESS,
  ENERGY,
  FEED,
  FORCE,
  LENGTH,
  MASS,
  PHYSICAL_KINDS,
  POWER,
  SPINDLE_SPEED,
  TEMPERATURE,
  TIME,
  VOLTAGE,
  angleQuantity,
  describeDimension,
  describeKind,
  dimensionOfKind,
  dimensionsEqual,
  dimensionsEqualIgnoringAngle,
  feedQuantity,
  isPhysicalKind,
  lengthQuantity,
  makeDimension,
  numberQuantity,
  spindleSpeedQuantity,
  timeQuantity,
  type Dimension,
  type GeometricKind,
  type PhysicalKind,
  type Quantity,
  type QuantityKind,
} from './dimension';
export {
  FUNCTION_NAMES,
  MEASURE_FUNCTION_NAMES,
  evaluate,
  evaluateParsed,
  evaluateParsedQuantity,
  evaluateQuantity,
  parseAngle,
  parseFeed,
  parseLength,
  parseQuantity,
  parseSpindleSpeed,
  type EvaluateOptions,
  type EvaluationContext,
  type MeasureFunction,
  type MeasureLookup,
  type MeasureRequest,
  type VariableLookup,
} from './evaluate';
export {
  formatAngle,
  formatFeed,
  formatLength,
  formatNumber,
  formatSpindleSpeed,
  slopeDisplayUnit,
  type AngleFormat,
  type DecimalLengthFormat,
  type FeedFormat,
  type FractionDenominator,
  type FractionalLengthFormat,
  type LengthFormat,
} from './format';
export {
  CONSTANT_NAMES,
  MAX_NESTING,
  MAX_TREE_DEPTH,
  parseExpression,
  type ParseOptions,
} from './parser';
export {
  defaultDisplayUnit,
  displayUnitsOf,
  formatQuantity,
  fromDisplayUnit,
  resolveDisplayUnit,
  toDisplayUnit,
  unitSystemOf,
  type QuantityDisplayUnits,
  type QuantityFormat,
  type UnitSystem,
} from './quantities';
export { physicalQuantity, quantityFromSI, quantityToSI } from './si';
export {
  collectMeasures,
  collectReferences,
  findMeasures,
  findReferences,
  isValidVariableName,
  type MeasureReference,
  type QuotedFace,
  type VariableReference,
} from './references';
export type { Result, UnitsError, UnitsErrorCode } from './result';
export {
  MM_PER_FOOT,
  MM_PER_INCH,
  RAD_PER_DEG,
  SECONDS_PER_MINUTE,
  angleUnitFactor,
  fromMillimetres,
  fromRadians,
  lengthUnitFactor,
  toMillimetres,
  toRadians,
  PHYSICAL_UNIT_NAMES,
  type AngleUnit,
  type LengthUnit,
} from './units';
