import { expect, test, type Page } from '@playwright/test';
import { clickWorld, settle } from './helpers';
import { clickSketch, features, newSketch, rectangle, sketchIdle, tool } from './sketch-helpers';

// A part built entirely through the UI, regenerated by the real regen worker: a sketch, an
// extrusion of it, a fillet on an edge picked in the viewport, then a sketch on the top face
// (stored as a reference to the face) cut through the part.

async function openEmpty(page: Page) {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByTestId('empty-hint')).toBeVisible({ timeout: 90_000 });
  await page.waitForFunction(() => window.__manufakture!.model.getState().generation > 0);
  return errors;
}

/** Wait until the model is regenerated from the open document; its statuses by feature. */
async function statuses(page: Page): Promise<Record<string, string>> {
  await page.waitForFunction(() => {
    const hooks = window.__manufakture!;
    const m = hooks.model.getState();
    const doc = hooks.document.getState().document;
    const shown = m.parts[0]?.features.map((f) => f.featureId).join() ?? '';
    return !m.pending && shown === doc.parts[0]!.features.map((f) => f.id).join();
  });
  return page.evaluate(() =>
    Object.fromEntries(
      window.__manufakture!.model.getState().parts[0]!.features.map((f) => [f.featureId, f.status]),
    ),
  );
}

async function openTool(page: Page, name: string) {
  await page
    .getByRole('toolbar', { name: 'Features' })
    .getByRole('button', { name, exact: true })
    .click();
  await expect(page.getByTestId('feature-dialog')).toBeVisible();
}

async function ok(page: Page) {
  await page.getByTestId('dialog-ok').click();
  await expect(page.getByTestId('feature-dialog')).toBeHidden();
}

async function bodyVolume(page: Page): Promise<number> {
  await page.evaluate(() => window.__manufakture!.selection.getState().clear());
  await page.waitForFunction(() => {
    const s = window.__manufakture!.measure.getState();
    return s.status === 'ready' && s.request?.targets.length === 0 && s.result?.body;
  });
  return page.evaluate(() => window.__manufakture!.measure.getState().result!.body!.volume);
}

test('sketch, extrude and fillet through the UI, then cut a hole sketched on a face', async ({
  page,
}) => {
  const errors = await openEmpty(page);

  // 1. A 40 x 25 rectangle on Top.
  await newSketch(page, 'Top (XY)');
  await rectangle(page, [0, 0], [40, 25]);
  await page.getByRole('button', { name: 'Finish sketch' }).click();
  await expect(page.getByTestId('feature-sketch#1')).toBeVisible();

  // 2. Extrude it 15 mm: select the sketch in the tree, then Extrude.
  await page.getByTestId('feature-sketch#1').click();
  await openTool(page, 'Extrude');
  await expect(page.getByTestId('field-sketch')).toHaveValue('sketch#1');
  await expect(page.getByTestId('field-operation')).toHaveValue('new');
  await page.getByTestId('field-distance').fill('15');
  await ok(page);
  expect(await statuses(page)).toEqual({ 'sketch#1': 'ok', 'extrude#1': 'ok' });
  await expect(page.getByTestId('feature-extrude#1')).toHaveAttribute('data-status', 'ok');
  let info = await page.evaluate(() => window.__manufakture!.viewport.info());
  expect(info.bodies.map((b) => [b.id, b.faces])).toEqual([['part#1/extrude#1', 6]]);
  expect(await bodyVolume(page)).toBeCloseTo(40 * 25 * 15, 1);

  // 3. Fillet the top front edge, picked in the viewport.
  await page.evaluate(() => window.__manufakture!.viewport.setStandardView('iso', false));
  await settle(page);
  await openTool(page, 'Fillet');
  await clickWorld(page, [20, 0, 15]);
  await expect(page.getByTestId('ref-edges')).toContainText(
    'extrude#1:cap:end | extrude#1:side:e1',
  );
  await page.getByTestId('field-radius').fill('3');
  await ok(page);
  expect(await statuses(page)).toEqual({ 'sketch#1': 'ok', 'extrude#1': 'ok', 'fillet#1': 'ok' });
  const fillet = (await features(page)).at(-1) as unknown as {
    edges: { id: string; ref: { faces: string[] } }[];
  };
  // Stored by the names of its faces, never a placeholder or an index.
  expect(fillet.edges).toEqual([
    { id: 'r1', ref: { faces: ['extrude#1:cap:end', 'extrude#1:side:e1'] } },
  ]);
  info = await page.evaluate(() => window.__manufakture!.viewport.info());
  expect(info.bodies[0]!.faces).toBe(7);
  const round = (9 - (9 * Math.PI) / 4) * 40;
  expect(await bodyVolume(page)).toBeCloseTo(40 * 25 * 15 - round, 1);

  // 4. A circle sketched on the top face, which the sketch stores as a reference.
  await clickWorld(page, [10, 18, 15]);
  await expect
    .poll(() =>
      page.evaluate(() =>
        window.__manufakture!.selection.getState().selected.map((i) => i.name ?? i.id),
      ),
    )
    .toEqual(['extrude#1:cap:end']);
  await newSketch(page, 'Selected face');
  await tool(page, 'Circle');
  await clickSketch(page, [20, 12.5]);
  await clickSketch(page, [24, 12.5]);
  await sketchIdle(page);
  await page.getByRole('button', { name: 'Finish sketch' }).click();
  const sketch2 = (await features(page)).at(-1)!;
  expect(sketch2.plane).toEqual({
    type: 'face',
    face: { id: 'r2', ref: { face: 'extrude#1:cap:end' } },
  });

  // 5. Cut it through the part, downwards.
  await page.getByTestId('feature-sketch#2').click();
  await openTool(page, 'Extrude');
  await expect(page.getByTestId('field-sketch')).toHaveValue('sketch#2');
  await expect(page.getByTestId('field-operation')).toHaveValue('add');
  await page.getByTestId('field-operation').selectOption('cut');
  await page.getByTestId('field-extent').selectOption('throughAll');
  await page.getByLabel('Opposite direction').check();
  await ok(page);
  expect(await statuses(page)).toEqual({
    'sketch#1': 'ok',
    'extrude#1': 'ok',
    'fillet#1': 'ok',
    'sketch#2': 'ok',
    'extrude#2': 'ok',
  });
  expect(await bodyVolume(page)).toBeCloseTo(40 * 25 * 15 - round - Math.PI * 16 * 15, 0);

  // Every step is one undo: the cut goes, and the part is back to the filleted block.
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  expect(await statuses(page)).toMatchObject({ 'fillet#1': 'ok', 'sketch#2': 'ok' });
  expect(await bodyVolume(page)).toBeCloseTo(40 * 25 * 15 - round, 1);
  expect(errors).toEqual([]);
});
