import { expect, test, type Page } from '@playwright/test';
import { openScene } from './helpers';

// The feature tree on the demo part (Sketch 1, Extrude 1, Fillet 1, Sketch 2, and the Hole cut
// from it), regenerated by the real regen worker. Every action is a document command, so Undo
// takes each back in turn, and the regenerated part follows.

const row = (page: Page, id: string) => page.getByTestId(`feature-${id}`);

function order(page: Page): Promise<string[]> {
  return page.evaluate(() =>
    window.__manufakture!.document.getState().document.parts[0]!.features.map((f) => f.id),
  );
}

/** Wait until the model is regenerated from the open document, and return its statuses. */
async function statuses(page: Page): Promise<Record<string, string>> {
  await page.waitForFunction(() => {
    const hooks = window.__manufakture!;
    const m = hooks.model.getState();
    return !m.pending && m.generation > 0;
  });
  return page.evaluate(() =>
    Object.fromEntries(
      window.__manufakture!.model.getState().parts[0]!.features.map((f) => [f.featureId, f.status]),
    ),
  );
}

async function faces(page: Page): Promise<number> {
  await statuses(page);
  return page.evaluate(() => window.__manufakture!.viewport.info().bodies[0]!.faces);
}

/** Drag with real pointer moves from the centre of one element to a point. */
async function drag(page: Page, from: { x: number; y: number }, to: { x: number; y: number }) {
  await page.mouse.move(from.x, from.y);
  await page.mouse.down();
  const steps = 8;
  for (let i = 1; i <= steps; i++) {
    await page.mouse.move(
      from.x + ((to.x - from.x) * i) / steps,
      from.y + ((to.y - from.y) * i) / steps,
    );
  }
  await page.mouse.up();
}

async function centre(page: Page, testId: string) {
  const box = (await page.getByTestId(testId).boundingBox())!;
  return {
    x: box.x + box.width / 3,
    y: box.y + box.height / 2,
    top: box.y,
    bottom: box.y + box.height,
  };
}

async function undo(page: Page) {
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
}

test('reorder two independent features, suppress one, roll back, and undo each step', async ({
  page,
}) => {
  await openScene(page, '?scene=demo', 90_000);
  const allOk = {
    'sketch#1': 'ok',
    'extrude#1': 'ok',
    'fillet#1': 'ok',
    'sketch#2': 'ok',
    'extrude#2': 'ok',
  };
  expect(await statuses(page)).toEqual(allOk);
  const full = await faces(page);

  // 1. Reorder: drag Sketch 2 (the hole's sketch) to the top; it depends on nothing.
  const s2 = await centre(page, 'feature-sketch#2');
  const s1 = await centre(page, 'feature-sketch#1');
  await drag(page, s2, { x: s1.x, y: s1.top + 2 });
  expect(await order(page)).toEqual(['sketch#2', 'sketch#1', 'extrude#1', 'fillet#1', 'extrude#2']);
  expect(await statuses(page)).toEqual(allOk);
  expect(await faces(page)).toBe(full);

  // A move that breaks a dependency is refused, with the reason.
  const fillet = await centre(page, 'feature-fillet#1');
  const block = await centre(page, 'feature-extrude#1');
  await drag(page, fillet, { x: block.x, y: block.top + 2 });
  await expect(page.getByTestId('tree-message')).toContainText(
    'Fillet 1 cannot move above Extrude 1: it is built from it.',
  );
  expect(await order(page)).toEqual(['sketch#2', 'sketch#1', 'extrude#1', 'fillet#1', 'extrude#2']);

  // 2. Suppress the hole: the part loses the hole's faces.
  await row(page, 'extrude#2').hover();
  await page.getByRole('button', { name: 'Suppress Hole' }).click();
  await expect(row(page, 'extrude#2')).toHaveAttribute('data-status', 'suppressed');
  expect((await statuses(page))['extrude#2']).toBe('suppressed');
  const noHole = await faces(page);
  expect(noHole).toBeLessThan(full);

  // Hovering a feature highlights it, and its faces, in the viewport.
  await row(page, 'fillet#1').hover();
  await expect
    .poll(() => page.evaluate(() => window.__manufakture!.selection.getState().hovered))
    .toMatchObject({ kind: 'feature', id: 'fillet#1' });

  // 3. Roll back above the fillet: drag the bar up between Extrude 1 and Fillet 1.
  const bar = await centre(page, 'rollback-bar');
  const target = await centre(page, 'feature-fillet#1');
  await drag(page, bar, { x: bar.x, y: target.top + 3 });
  await expect(row(page, 'fillet#1')).toHaveAttribute('data-status', 'rolled-back');
  await expect(page.getByTestId('rollback-bar')).toHaveAttribute('aria-valuenow', '3');
  expect(await statuses(page)).toMatchObject({ 'fillet#1': 'rolled-back', 'extrude#1': 'ok' });
  // A plain block: six faces.
  expect(await faces(page)).toBe(6);

  // Undo each step, newest first: the rollback, the suppression, the move.
  await undo(page);
  await expect(page.getByTestId('rollback-bar')).toHaveAttribute('aria-valuenow', '5');
  expect(await faces(page)).toBe(noHole);
  await undo(page);
  await expect(row(page, 'extrude#2')).toHaveAttribute('data-status', 'ok');
  expect(await faces(page)).toBe(full);
  await undo(page);
  expect(await order(page)).toEqual(['sketch#1', 'extrude#1', 'fillet#1', 'sketch#2', 'extrude#2']);
  expect(await statuses(page)).toEqual(allOk);
  expect(await faces(page)).toBe(full);
});

test('a feature whose reference is lost shows the kernel message and offers a re-pick', async ({
  page,
}) => {
  await openScene(page, '?scene=demo', 90_000);
  // Point the fillet's first edge at faces that do not exist, as a broken edit would.
  await page.evaluate(() => {
    const store = window.__manufakture!.document;
    const fillet = store.getState().document.parts[0]!.features[2]! as unknown as {
      edges: { id: string; ref: { faces: string[] } }[];
    };
    const edges = fillet.edges.map((e, i) =>
      i === 0 ? { ...e, ref: { faces: ['extrude#1:cap:end', 'extrude#1:side:e9'] } } : e,
    );
    store.getState().execute({
      type: 'editFeature',
      partId: 'part#1',
      feature: { ...(fillet as object), edges },
    });
  });
  await expect(row(page, 'fillet#1')).toHaveAttribute('data-status', 'error');
  await page.getByTestId('status-fillet#1').hover();
  const tip = page.getByTestId('feature-tip');
  await expect(tip).toContainText('re-pick');
  await expect(tip.getByRole('button', { name: 'Re-pick r1' })).toBeVisible();
  // The hole does not use the fillet: it still builds on the body the fillet passed through.
  expect((await statuses(page))['extrude#2']).toBe('ok');
});
