import { expect, test, type Page } from '@playwright/test';
import { clickSketch, newSketch, rectangle, sketchIdle, tool } from './sketch-helpers';

// A box driven by the variables table, built through the UI and regenerated by the real regen
// worker: #w and #d dimension the sketch, #h is the extrusion depth. Changing a variable in the
// table changes the geometry, rebuilding only the features that read it.

async function openEmpty(page: Page) {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByTestId('empty-hint')).toBeVisible({ timeout: 90_000 });
  await page.waitForFunction(() => window.__manufakture!.model.getState().generation > 0);
  return errors;
}

/** Wait until the model shows the open document; then every feature's status and whether it came from the cache. */
async function regenerated(
  page: Page,
): Promise<Record<string, { status: string; cached: boolean }>> {
  await page.waitForFunction(() => {
    const hooks = window.__manufakture!;
    const m = hooks.model.getState();
    return !m.pending && m.document === hooks.document.getState().document;
  });
  return page.evaluate(() =>
    Object.fromEntries(
      window
        .__manufakture!.model.getState()
        .parts[0]!.features.map((f) => [f.featureId, { status: f.status, cached: f.cached }]),
    ),
  );
}

async function bodyVolume(page: Page): Promise<number> {
  await page.evaluate(() => window.__manufakture!.selection.getState().clear());
  await page.waitForFunction(() => {
    const s = window.__manufakture!.measure.getState();
    return s.status === 'ready' && s.request?.targets.length === 0 && s.result?.body;
  });
  return page.evaluate(() => window.__manufakture!.measure.getState().result!.body!.volume);
}

const panel = (page: Page) => page.getByRole('complementary', { name: 'Variables' });

async function addVariable(page: Page, name: string, value: string) {
  await panel(page).getByTestId('variable-add').click();
  await page.getByTestId('variable-name').fill(name);
  await page.getByTestId('variable-expression').fill(value);
  await page.getByTestId('variable-save').click();
  await expect(page.getByTestId('variable-editor')).toBeHidden();
}

async function editVariable(page: Page, name: string, value: string) {
  await panel(page)
    .getByRole('button', { name: `Edit #${name}` })
    .click();
  await page.getByTestId('variable-expression').fill(value);
  await page.getByTestId('variable-save').click();
  await expect(page.getByTestId('variable-editor')).toBeHidden();
}

test('a box driven by #w, #d and #h follows the variables table', async ({ page }) => {
  const errors = await openEmpty(page);

  // 1. The variables. A bare number typed as a length gets its unit written in; `#d - 10` is a
  // length already (10 is read in the display unit), so it stays as typed.
  await addVariable(page, 'w', '40');
  await addVariable(page, 'd', '25');
  await addVariable(page, 'h', '#d - 10');
  await expect(page.getByTestId('variable-w-value')).toHaveText('40.00 mm');
  await expect(page.getByTestId('variable-h-value')).toHaveText('15.00 mm');
  await expect(page.getByTestId('variable-w')).toContainText('40 mm');
  await expect(page.getByTestId('variable-h')).toContainText('#d - 10');

  // 2. Variables that read each other are refused, with the loop spelled out.
  await addVariable(page, 'a', '#w / 2');
  await panel(page).getByRole('button', { name: 'Edit #w' }).click();
  await page.getByTestId('variable-expression').fill('#a * 2');
  await expect(page.getByTestId('variable-expression-note')).toHaveText(
    'Variables cannot read each other in a loop: #w -> #a -> #w.',
  );
  await page.getByTestId('variable-save').click();
  await expect(page.getByTestId('variable-editor')).toBeVisible();
  await page.getByTestId('variable-expression').press('Escape');
  await expect(page.getByTestId('variable-editor')).toBeHidden();
  await expect(page.getByTestId('variable-w')).toContainText('40 mm');
  // An unused variable goes straight away.
  await panel(page).getByRole('button', { name: 'Delete #a' }).click();
  await expect(page.getByTestId('variable-a')).toHaveCount(0);

  // 3. A 40 x 25 rectangle, dimensioned by #w and #d picked from the completion list.
  await newSketch(page, 'Top (XY)');
  await rectangle(page, [0, 0], [40, 25]);
  await tool(page, 'Dimension');
  await clickSketch(page, [20, 0]);
  await clickSketch(page, [20, -8]);
  const input = page.getByTestId('dimension-input');
  await expect(input).toBeFocused();
  await input.fill('#');
  await expect(input).toHaveAttribute('aria-expanded', 'true');
  await expect(page.getByTestId('dimension-input-options').getByRole('option')).toHaveText([
    '#w40.00 mm',
    '#d25.00 mm',
    '#h15.00 mm',
  ]);
  await input.press('Enter'); // takes #w; the box stays open
  await expect(input).toHaveValue('#w');
  await expect(input).toHaveAttribute('aria-expanded', 'false');
  await input.press('Enter');
  await expect(input).toBeHidden();
  await sketchIdle(page);
  await tool(page, 'Dimension');
  await clickSketch(page, [40, 12.5]);
  await clickSketch(page, [48, 12.5]);
  // A name typed in full has nothing to complete: Enter sets the dimension.
  await input.fill('#d');
  await expect(input).toHaveAttribute('aria-expanded', 'false');
  await input.press('Enter');
  await expect(input).toBeHidden();
  await sketchIdle(page);
  await page.getByRole('button', { name: 'Finish sketch' }).click();

  // 4. Extrude it by #h; Enter in the completion list does not apply the dialog.
  await page.getByTestId('feature-sketch#1').click();
  await page
    .getByRole('toolbar', { name: 'Features' })
    .getByRole('button', { name: 'Extrude', exact: true })
    .click();
  const depth = page.getByTestId('field-distance');
  await depth.fill('#');
  await depth.press('ArrowDown');
  await depth.press('ArrowDown');
  await depth.press('Enter');
  await expect(depth).toHaveValue('#h');
  await expect(page.getByTestId('feature-dialog')).toBeVisible();
  await expect(page.getByTestId('field-distance-note')).toHaveText('= 15.00 mm');
  await page.getByTestId('dialog-ok').click();
  await expect(page.getByTestId('feature-dialog')).toBeHidden();
  expect(await regenerated(page)).toMatchObject({
    'sketch#1': { status: 'ok' },
    'extrude#1': { status: 'ok' },
  });
  expect(await bodyVolume(page)).toBeCloseTo(40 * 25 * 15, 1);

  // 5. The table shows where each variable is used.
  await page.getByTestId('variable-d-uses').locator('summary').click();
  await expect(page.getByTestId('variable-d-uses')).toContainText('#h');
  await expect(page.getByTestId('variable-d-uses')).toContainText(/Sketch 1: dimension k\d+/);

  // 6. A new width rebuilds the sketch and the extrusion.
  await editVariable(page, 'w', '50');
  expect(await regenerated(page)).toEqual({
    'sketch#1': { status: 'ok', cached: false },
    'extrude#1': { status: 'ok', cached: false },
  });
  expect(await bodyVolume(page)).toBeCloseTo(50 * 25 * 15, 1);

  // 7. A new depth rebuilds only the extrusion: the sketch comes from the cache.
  await editVariable(page, 'h', '20');
  expect(await regenerated(page)).toEqual({
    'sketch#1': { status: 'ok', cached: true },
    'extrude#1': { status: 'ok', cached: false },
  });
  expect(await bodyVolume(page)).toBeCloseTo(50 * 25 * 20, 1);

  // 8. #h is in use: deleting it offers to write its value into the extrusion instead.
  await panel(page).getByRole('button', { name: 'Delete #h' }).click();
  await expect(page.getByTestId('variable-blocked')).toContainText('#h is used in 1 place');
  await page.getByTestId('variable-replace').click();
  await expect(page.getByTestId('variable-h')).toHaveCount(0);
  const extrude = await page.evaluate(
    () =>
      window.__manufakture!.document.getState().document.parts[0]!.features[1] as unknown as {
        extent: { distance: { source: string } };
      },
  );
  expect(extrude.extent.distance.source).toBe('20mm');
  // The same value: nothing to rebuild.
  expect(await regenerated(page)).toMatchObject({ 'extrude#1': { status: 'ok', cached: true } });
  expect(await bodyVolume(page)).toBeCloseTo(50 * 25 * 20, 1);
  // One undo brings the variable back.
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByTestId('variable-h-value')).toHaveText('20.00 mm');
  expect(errors).toEqual([]);
});
