// The T0.3 own-wrapper design (spikes/kernel-wrapper/src/own/kernel.ts),
// copied and extended for the topological naming spike:
//
// - History entries name their outputs with a kind, so one entry can say
//   "this input edge became these result edges" (Modified) or "this input
//   edge generated this result face" (Generated). T0.3 mapped everything to
//   result faces only and dropped Modified for edges.
// - History is collected for input faces, edges and vertices of every
//   operand, including entries with no face output.
// - `extrude` builds a profile face from a sketch loop and returns which
//   result face every profile edge generated, plus the two caps: the raw
//   material for "extrude#1:side:e2" style names.
// - `topology` reports faces, edges and vertices of a shape with their
//   adjacency and a little geometry, so names can be derived for edges from
//   their adjacent faces and tests can check where things landed.
//
// As in T0.3: shapes live in an arena and cross the API as integer ids, every
// temporary OCCT object is owned by a Scope and released before delete (T0.2),
// and failures are KernelErrors with the decoded OCCT exception.

import type {
  OpenCascadeInstance,
  TopAbs_ShapeEnum,
  TopoDS_Edge,
  TopoDS_Face,
  TopoDS_Shape,
  TopoDS_Vertex,
  gp_Trsf,
} from 'libcascade/single/init';

export type Oc = OpenCascadeInstance;

declare const shapeIdBrand: unique symbol;
/** A shape in the kernel's arena. Only valid on the kernel that returned it. */
export type ShapeId = number & { readonly [shapeIdBrand]: true };

export type SubShapeKind = 'face' | 'edge' | 'vertex';
export type Vec3 = readonly [number, number, number];

/** A sub-shape of a given shape, by 1-based index in TopExp.MapShapes order. */
export interface SubShapeRef {
  kind: SubShapeKind;
  index: number;
}

/**
 * What an operation did to one sub-shape of one input. `operand` is the
 * position of the input in the call (0 = the shape, 1 = the tool). Outputs
 * are sub-shapes of the result, of any kind.
 */
export interface HistoryEntry {
  operand: number;
  input: SubShapeRef;
  /** Index of the same sub-shape (same kind) in the result when it passed through untouched, else 0. */
  kept: number;
  /** Result sub-shapes this input became (OCCT Modified). */
  modified: SubShapeRef[];
  /** Result sub-shapes this input gave rise to (OCCT Generated). */
  generated: SubShapeRef[];
  deleted: boolean;
}

export interface OperationResult {
  shape: ShapeId;
  history: HistoryEntry[];
}

/** A right-handed placement: y = normal x xDir. */
export interface Frame {
  origin: Vec3;
  xDir: Vec3;
  normal: Vec3;
}

/** One closed sketch loop in frame coordinates. Polygon edge i runs from point i to point i+1. */
export type Loop =
  | { kind: 'polygon'; points: ReadonlyArray<readonly [number, number]> }
  | { kind: 'circle'; center: readonly [number, number]; radius: number };

export interface ExtrudeResult {
  shape: ShapeId;
  /** Result face index of the cap at `from` (the profile itself). */
  capStart: number;
  /** Result face index of the cap at `to`. */
  capEnd: number;
  /** Result face index generated by each loop edge, in loop order. */
  sides: number[];
}

export interface FaceInfo {
  index: number;
  surface: string;
  centroid: Vec3;
  area: number;
  /** Outward normal, planes only. */
  normal: Vec3 | null;
  /** Axis direction, cylinders only. */
  axis: Vec3 | null;
  /** Cylinders only. */
  radius: number | null;
}

export interface EdgeInfo {
  index: number;
  /** Adjacent faces, unique, ascending. A seam edge lists its one face once. */
  faces: number[];
  seam: boolean;
  curve: string;
  midpoint: Vec3;
  length: number;
  /** Vertex indices (one for a closed edge). */
  vertices: number[];
}

export interface VertexInfo {
  index: number;
  point: Vec3;
  /** Faces around the vertex, unique, ascending. */
  faces: number[];
}

export interface Topology {
  faces: FaceInfo[];
  edges: EdgeInfo[];
  vertices: VertexInfo[];
}

export interface MeshData {
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  /** Per B-rep face (result face order): [firstIndex, indexCount]. */
  faceRanges: Uint32Array;
}

export class KernelError extends Error {
  readonly operation: string;
  constructor(operation: string, message: string) {
    super(`${operation}: ${message}`);
    this.name = 'KernelError';
    this.operation = operation;
  }
}

interface Deletable {
  delete(): void;
}

type Releasable = Deletable & Record<string, unknown>;

/**
 * Release what an object owns without relying on its destructor (libcascade
 * 3.0.x registers an empty destructor for 2102 classes; see T0.2).
 */
function release(oc: Oc, item: Deletable): void {
  const o = item as Releasable;
  const name = (o.constructor as { name?: string }).name ?? '';
  if (name.startsWith('TopoDS_')) {
    (o.Nullify as () => void).call(o);
  } else if (name === 'TopLoc_Location') {
    (o.Clear as () => void).call(o);
  } else if (name.startsWith('BRepAlgoAPI_')) {
    (o.Clear as () => void).call(o);
    const empty = new oc.NCollection_List_TopoDS_Shape();
    try {
      (o.SetArguments as (l: unknown) => void).call(o, empty);
      if (typeof o.SetTools === 'function') (o.SetTools as (l: unknown) => void).call(o, empty);
    } finally {
      empty.delete();
    }
  } else if (name === 'BRepFilletAPI_MakeFillet') {
    (o.Reset as () => void).call(o);
  }
}

/** Owns embind objects and releases them in reverse order. */
export class Scope {
  private readonly items: Deletable[] = [];
  private readonly oc: Oc;
  constructor(oc: Oc) {
    this.oc = oc;
  }
  own<T extends Deletable>(item: T): T {
    this.items.push(item);
    return item;
  }
  free(item: Deletable): void {
    try {
      release(this.oc, item);
    } finally {
      item.delete();
    }
  }
  dispose(): void {
    let first: unknown = null;
    for (let i = this.items.length - 1; i >= 0; i--) {
      try {
        this.free(this.items[i]!);
      } catch (error) {
        first ??= error;
      }
    }
    this.items.length = 0;
    if (first !== null) throw first;
  }
}

type IndexedMap = InstanceType<Oc['NCollection_IndexedMap_TopoDS_Shape_TopTools_ShapeMapHasher']>;
type ShapeList = InstanceType<Oc['NCollection_List_TopoDS_Shape']>;

/** The OCCT history interface shared by BRepBuilderAPI_MakeShape and BRepAlgoAPI builders. */
interface HistorySource {
  Modified(x: TopoDS_Shape): ShapeList;
  Generated(x: TopoDS_Shape): ShapeList;
  IsDeleted(x: TopoDS_Shape): boolean;
}

const KINDS: SubShapeKind[] = ['face', 'edge', 'vertex'];

export class Kernel {
  readonly oc: Oc;
  private readonly arena = new Map<number, TopoDS_Shape>();
  private nextId = 1;

  constructor(oc: Oc) {
    this.oc = oc;
  }

  // Lifetime ------------------------------------------------------------------

  get shapeCount(): number {
    return this.arena.size;
  }

  release(id: ShapeId): void {
    const shape = this.arena.get(id);
    if (!shape) return;
    this.arena.delete(id);
    shape.Nullify();
    shape.delete();
  }

  // Construction ----------------------------------------------------------------

  /**
   * Extrude one sketch loop placed in `frame`: the profile sits at `from`
   * along the frame normal and is swept to `to`.
   */
  extrude(frame: Frame, loop: Loop, from: number, to: number): ExtrudeResult {
    return this.op('extrude', (s) => {
      if (Math.abs(to - from) < 1e-9) throw new Error('zero-length extrusion');
      const oc = this.oc;
      const [ox, oy, oz] = frame.origin;
      const n = frame.normal;
      const x = frame.xDir;
      const y = cross(n, x);
      const at = (u: number, v: number): Vec3 => [
        ox + u * x[0] + v * y[0] + from * n[0],
        oy + u * x[1] + v * y[1] + from * n[1],
        oz + u * x[2] + v * y[2] + from * n[2],
      ];
      const pnt = (p: Vec3) => s.own(new oc.gp_Pnt(p[0], p[1], p[2]));
      const dir = (d: Vec3) => s.own(new oc.gp_Dir(d[0], d[1], d[2]));

      const edges: TopoDS_Edge[] = [];
      if (loop.kind === 'polygon') {
        const vertices = loop.points.map(([u, v]) =>
          s.own(s.own(new oc.BRepBuilderAPI_MakeVertex(pnt(at(u, v)))).Vertex()),
        );
        for (let i = 0; i < vertices.length; i++) {
          const maker = s.own(
            new oc.BRepBuilderAPI_MakeEdge(vertices[i]!, vertices[(i + 1) % vertices.length]!),
          );
          if (!maker.IsDone()) throw new Error(`profile edge ${i} failed`);
          edges.push(s.own(maker.Edge()));
        }
      } else {
        const ax2 = s.own(new oc.gp_Ax2(pnt(at(loop.center[0], loop.center[1])), dir(n), dir(x)));
        const circ = s.own(new oc.gp_Circ(ax2, loop.radius));
        const maker = s.own(new oc.BRepBuilderAPI_MakeEdge(circ));
        if (!maker.IsDone()) throw new Error('profile circle failed');
        edges.push(s.own(maker.Edge()));
      }
      const wireMaker = s.own(new oc.BRepBuilderAPI_MakeWire());
      for (const e of edges) wireMaker.Add(e);
      if (!wireMaker.IsDone()) throw new Error('profile wire failed');
      const wire = s.own(wireMaker.Wire());
      const faceMaker = s.own(new oc.BRepBuilderAPI_MakeFace(wire, true));
      if (!faceMaker.IsDone()) throw new Error('profile face failed');
      const face = s.own(faceMaker.Face());
      const d = to - from;
      const vec = s.own(new oc.gp_Vec(n[0] * d, n[1] * d, n[2] * d));
      const prism = s.own(new oc.BRepPrimAPI_MakePrism(face, vec, false, true));
      if (!prism.IsDone()) throw new Error('prism failed');
      const result = prism.Shape();
      return this.storeWith(result, (id) => {
        const faces = mapShapes(oc, s, result, 'face');
        const sides = edges.map((e, i) => {
          const generated = s.own(prism.Generated(e));
          if (generated.Size() !== 1) {
            throw new Error(`profile edge ${i} generated ${generated.Size()} faces`);
          }
          return faces.FindIndex(s.own(generated.First()));
        });
        const capStart = faces.FindIndex(s.own(prism.FirstShape()));
        const capEnd = faces.FindIndex(s.own(prism.LastShape()));
        if (capStart === 0 || capEnd === 0 || sides.includes(0)) {
          throw new Error('prism history did not resolve to result faces');
        }
        return { shape: id, capStart, capEnd, sides };
      });
    });
  }

  // Operations with history -------------------------------------------------------

  /**
   * Boolean with full history. `simplify` runs OCCT's SimplifyResult
   * (unify same-domain faces and edges), whose history is merged into the
   * builder's, so merged faces show up as several inputs with one result.
   */
  boolean(
    op: 'cut' | 'fuse',
    shape: ShapeId,
    tool: ShapeId,
    options: { simplify?: boolean } = {},
  ): OperationResult {
    return this.op(op, (s) => {
      const a = this.get(shape);
      const b = this.get(tool);
      const builder =
        op === 'cut'
          ? s.own(new this.oc.BRepAlgoAPI_Cut(a, b))
          : s.own(new this.oc.BRepAlgoAPI_Fuse(a, b));
      if (!builder.IsDone() || builder.HasErrors()) throw new Error('boolean failed');
      if (options.simplify) builder.SimplifyResult(true, true);
      const result = builder.Shape();
      return this.storeWith(result, (id) => ({
        shape: id,
        history: collectHistory(this.oc, s, builder, [a, b], result),
      }));
    });
  }

  /** Fillet the given edges (1-based indices into the shape's edge map). */
  fillet(shape: ShapeId, radius: number, edges: number[]): OperationResult {
    return this.op('fillet', (s) => {
      const input = this.get(shape);
      const edgeMap = mapShapes(this.oc, s, input, 'edge');
      const maker = s.own(new this.oc.BRepFilletAPI_MakeFillet(input));
      for (const i of edges) {
        if (i < 1 || i > edgeMap.Extent()) throw new Error(`no edge ${i}`);
        const edge: TopoDS_Edge = s.own(this.oc.TopoDS.Edge(s.own(edgeMap.FindKey(i))));
        maker.Add(radius, edge);
      }
      maker.Build();
      if (!maker.IsDone()) throw new Error('fillet failed');
      const result = maker.Shape();
      return this.storeWith(result, (id) => ({
        shape: id,
        history: collectHistory(this.oc, s, maker, [input], result),
      }));
    });
  }

  // Queries -----------------------------------------------------------------------

  volume(shape: ShapeId): number {
    return this.op('volume', (s) => {
      const props = s.own(new this.oc.GProp_GProps());
      this.oc.BRepGProp.VolumeProperties(this.get(shape), props, false, false, false);
      return props.Mass();
    });
  }

  isValid(shape: ShapeId): boolean {
    return this.op('isValid', (s) => {
      const analyzer = s.own(new this.oc.BRepCheck_Analyzer(this.get(shape), true, false));
      return analyzer.IsValid();
    });
  }

  topology(shape: ShapeId): Topology {
    return this.op('topology', (s) => {
      const oc = this.oc;
      const body = this.get(shape);
      const faceMap = mapShapes(oc, s, body, 'face');
      const edgeMap = mapShapes(oc, s, body, 'edge');
      const vertexMap = mapShapes(oc, s, body, 'vertex');
      const ancestors = (kind: SubShapeKind) => {
        const m = s.own(
          new oc.NCollection_IndexedDataMap_TopoDS_Shape_NCollection_List_TopoDS_Shape_TopTools_ShapeMapHasher(),
        );
        oc.TopExp.MapShapesAndAncestors(
          body,
          shapeEnum(oc, kind),
          oc.TopAbs_ShapeEnum.TopAbs_FACE,
          m,
        );
        return m;
      };
      const edgeFaces = ancestors('edge');
      const vertexFaces = ancestors('vertex');
      const faceIndices = (list: ShapeList): { unique: number[]; total: number } => {
        const copy = s.own(new oc.NCollection_List_TopoDS_Shape(list));
        const out = new Set<number>();
        let total = 0;
        while (copy.Size() > 0) {
          out.add(faceMap.FindIndex(s.own(copy.First())));
          total++;
          copy.RemoveFirst();
        }
        return { unique: [...out].sort((p, q) => p - q), total };
      };

      const faces: FaceInfo[] = [];
      for (let i = 1; i <= faceMap.Extent(); i++) {
        const fs = new Scope(oc);
        try {
          const face: TopoDS_Face = fs.own(oc.TopoDS.Face(fs.own(faceMap.FindKey(i))));
          const props = fs.own(new oc.GProp_GProps());
          oc.BRepGProp.SurfaceProperties(face, props, false, false);
          const adaptor = fs.own(new oc.BRepAdaptor_Surface(face, true));
          const type = adaptor.GetType();
          const reversed = face.Orientation() === oc.TopAbs_Orientation.TopAbs_REVERSED;
          let normal: Vec3 | null = null;
          let axis: Vec3 | null = null;
          let radius: number | null = null;
          if (type === oc.GeomAbs_SurfaceType.GeomAbs_Plane) {
            const pln = fs.own(adaptor.Plane());
            const ax1 = fs.own(pln.Axis());
            const d = fs.own(ax1.Direction());
            const sign = reversed ? -1 : 1;
            normal = [sign * d.X(), sign * d.Y(), sign * d.Z()];
          } else if (type === oc.GeomAbs_SurfaceType.GeomAbs_Cylinder) {
            const cyl = fs.own(adaptor.Cylinder());
            const ax1 = fs.own(cyl.Axis());
            const d = fs.own(ax1.Direction());
            axis = [d.X(), d.Y(), d.Z()];
            radius = cyl.Radius();
          }
          faces.push({
            index: i,
            surface: type.replace('GeomAbs_', '').toLowerCase(),
            centroid: point(fs.own(props.CentreOfMass())),
            area: props.Mass(),
            normal,
            axis,
            radius,
          });
        } finally {
          fs.dispose();
        }
      }

      const edges: EdgeInfo[] = [];
      for (let i = 1; i <= edgeMap.Extent(); i++) {
        const es = new Scope(oc);
        try {
          const key = es.own(edgeMap.FindKey(i));
          const edge: TopoDS_Edge = es.own(oc.TopoDS.Edge(key));
          const adjacent = faceIndices(edgeFaces.FindFromIndex(edgeFaces.FindIndex(edge)));
          const curve = es.own(new oc.BRepAdaptor_Curve(edge));
          const mid = (curve.FirstParameter() + curve.LastParameter()) / 2;
          const props = es.own(new oc.GProp_GProps());
          oc.BRepGProp.LinearProperties(edge, props, false, false);
          const first: TopoDS_Vertex = es.own(oc.TopExp.FirstVertex(edge, false));
          const last: TopoDS_Vertex = es.own(oc.TopExp.LastVertex(edge, false));
          const vertices = [vertexMap.FindIndex(first), vertexMap.FindIndex(last)];
          edges.push({
            index: i,
            faces: adjacent.unique,
            seam: adjacent.unique.length < adjacent.total,
            curve: curve.GetType().replace('GeomAbs_', '').toLowerCase(),
            midpoint: point(es.own(curve.Value(mid))),
            length: props.Mass(),
            vertices: [...new Set(vertices.filter((v) => v > 0))],
          });
        } finally {
          es.dispose();
        }
      }

      const vertices: VertexInfo[] = [];
      for (let i = 1; i <= vertexMap.Extent(); i++) {
        const vs = new Scope(oc);
        try {
          const vertex: TopoDS_Vertex = vs.own(oc.TopoDS.Vertex(vs.own(vertexMap.FindKey(i))));
          vertices.push({
            index: i,
            point: point(vs.own(oc.BRep_Tool.Pnt(vertex))),
            faces: faceIndices(vertexFaces.FindFromIndex(vertexFaces.FindIndex(vertex))).unique,
          });
        } finally {
          vs.dispose();
        }
      }
      return { faces, edges, vertices };
    });
  }

  /** Mesh the shape per face in face-map order, so a face range lines up with a face name. */
  mesh(shape: ShapeId, linear: number, angular: number): MeshData {
    return this.op('mesh', (s) => {
      const body = this.get(shape);
      const mesher = s.own(
        new this.oc.BRepMesh_IncrementalMesh(body, linear, false, angular, false),
      );
      if (!mesher.IsDone()) throw new Error('meshing failed');
      const faces = mapShapes(this.oc, s, body, 'face');
      const chunks: Chunk[] = [];
      for (let i = 1; i <= faces.Extent(); i++) {
        const fs = new Scope(this.oc);
        try {
          chunks.push(
            extractFace(this.oc, fs, fs.own(this.oc.TopoDS.Face(fs.own(faces.FindKey(i))))),
          );
        } finally {
          fs.dispose();
        }
      }
      this.oc.BRepTools.Clean(body, true);
      return pack(chunks);
    });
  }

  // Internals ---------------------------------------------------------------------

  private op<T>(name: string, fn: (s: Scope) => T): T {
    const s = new Scope(this.oc);
    try {
      return fn(s);
    } catch (error) {
      throw this.toError(name, error);
    } finally {
      s.dispose();
    }
  }

  private toError(operation: string, error: unknown): Error {
    if (error instanceof KernelError) return error;
    if (typeof WebAssembly.Exception === 'function' && error instanceof WebAssembly.Exception) {
      try {
        const [type, message] = this.oc.getExceptionMessage(error);
        return new KernelError(operation, `OCCT ${type}: ${message}`);
      } finally {
        this.oc.decrementExceptionRefcount(error);
      }
    }
    return new KernelError(operation, error instanceof Error ? error.message : String(error));
  }

  private get(id: ShapeId): TopoDS_Shape {
    const shape = this.arena.get(id);
    if (!shape) throw new KernelError('get', `unknown shape id ${id}`);
    return shape;
  }

  private store(shape: TopoDS_Shape): ShapeId {
    const id = this.nextId++ as ShapeId;
    this.arena.set(id, shape);
    return id;
  }

  private storeWith<T>(shape: TopoDS_Shape, fn: (id: ShapeId) => T): T {
    const id = this.store(shape);
    try {
      return fn(id);
    } catch (error) {
      this.release(id);
      throw error;
    }
  }
}

function cross(a: Vec3, b: Vec3): Vec3 {
  return [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
}

function point(p: { X(): number; Y(): number; Z(): number }): Vec3 {
  return [p.X(), p.Y(), p.Z()];
}

/** Index every sub-shape of one kind, in TopExp.MapShapes order (1-based). */
function mapShapes(oc: Oc, s: Scope, shape: TopoDS_Shape, kind: SubShapeKind): IndexedMap {
  const map = s.own(new oc.NCollection_IndexedMap_TopoDS_Shape_TopTools_ShapeMapHasher());
  oc.TopExp.MapShapes(shape, shapeEnum(oc, kind), map);
  return map;
}

function shapeEnum(oc: Oc, kind: SubShapeKind): TopAbs_ShapeEnum {
  const e = oc.TopAbs_ShapeEnum;
  return kind === 'face' ? e.TopAbs_FACE : kind === 'edge' ? e.TopAbs_EDGE : e.TopAbs_VERTEX;
}

function kindOf(oc: Oc, shape: TopoDS_Shape): SubShapeKind | null {
  const t = shape.ShapeType();
  const e = oc.TopAbs_ShapeEnum;
  return t === e.TopAbs_FACE
    ? 'face'
    : t === e.TopAbs_EDGE
      ? 'edge'
      : t === e.TopAbs_VERTEX
        ? 'vertex'
        : null;
}

/**
 * Ask the builder what became of every face, edge and vertex of every input,
 * naming inputs and outputs by kind and index in the result.
 */
function collectHistory(
  oc: Oc,
  s: Scope,
  builder: HistorySource,
  inputs: TopoDS_Shape[],
  result: TopoDS_Shape,
): HistoryEntry[] {
  const resultMaps = {
    face: mapShapes(oc, s, result, 'face'),
    edge: mapShapes(oc, s, result, 'edge'),
    vertex: mapShapes(oc, s, result, 'vertex'),
  };
  const toRefs = (list: ShapeList): SubShapeRef[] => {
    const out: SubShapeRef[] = [];
    const copy = s.own(new oc.NCollection_List_TopoDS_Shape(list));
    while (copy.Size() > 0) {
      const item = s.own(copy.First());
      copy.RemoveFirst();
      const kind = kindOf(oc, item);
      if (kind === null) continue;
      const index = resultMaps[kind].FindIndex(item);
      if (index > 0 && !out.some((r) => r.kind === kind && r.index === index)) {
        out.push({ kind, index });
      }
    }
    return out.sort((p, q) => (p.kind === q.kind ? p.index - q.index : p.kind < q.kind ? -1 : 1));
  };
  const entries: HistoryEntry[] = [];
  inputs.forEach((input, operand) => {
    for (const kind of KINDS) {
      const map = mapShapes(oc, s, input, kind);
      for (let i = 1; i <= map.Extent(); i++) {
        const sub = s.own(map.FindKey(i));
        entries.push({
          operand,
          input: { kind, index: i },
          kept: resultMaps[kind].FindIndex(sub),
          modified: toRefs(s.own(builder.Modified(sub))),
          generated: toRefs(s.own(builder.Generated(sub))),
          deleted: builder.IsDeleted(sub),
        });
      }
    }
  });
  return entries;
}

interface Chunk {
  positions: number[];
  normals: number[];
  indices: number[];
}

function extractFace(oc: Oc, s: Scope, face: TopoDS_Face): Chunk {
  const loc = s.own(new oc.TopLoc_Location());
  const tri = oc.BRep_Tool.Triangulation(face, loc, 0);
  if (tri === null) return { positions: [], normals: [], indices: [] };
  s.own(tri);
  if (!tri.HasNormals()) oc.BRepLib_ToolTriangulatedShape.ComputeNormals(face, tri);
  const reversed = face.Orientation() === oc.TopAbs_Orientation.TopAbs_REVERSED;
  const trsf: gp_Trsf | null = loc.IsIdentity() ? null : s.own(loc.Transformation());
  const sign = reversed ? -1 : 1;
  const nbNodes = tri.NbNodes();
  const positions = new Array<number>(nbNodes * 3);
  const normals = new Array<number>(nbNodes * 3);
  for (let i = 1; i <= nbNodes; i++) {
    const p = tri.Node(i);
    const n = tri.Normal(i);
    try {
      if (trsf) {
        p.Transform(trsf);
        n.Transform(trsf);
      }
      const o = (i - 1) * 3;
      positions[o] = p.X();
      positions[o + 1] = p.Y();
      positions[o + 2] = p.Z();
      normals[o] = sign * n.X();
      normals[o + 1] = sign * n.Y();
      normals[o + 2] = sign * n.Z();
    } finally {
      s.free(p);
      s.free(n);
    }
  }
  const nbTris = tri.NbTriangles();
  const indices = new Array<number>(nbTris * 3);
  for (let i = 1; i <= nbTris; i++) {
    const t = tri.Triangle(i);
    try {
      const { theN1, theN2, theN3 } = t.Get();
      const o = (i - 1) * 3;
      indices[o] = theN1 - 1;
      indices[o + 1] = (reversed ? theN3 : theN2) - 1;
      indices[o + 2] = (reversed ? theN2 : theN3) - 1;
    } finally {
      s.free(t);
    }
  }
  return { positions, normals, indices };
}

function pack(chunks: Chunk[]): MeshData {
  let vertexCount = 0;
  let indexCount = 0;
  for (const c of chunks) {
    vertexCount += c.positions.length / 3;
    indexCount += c.indices.length;
  }
  const positions = new Float32Array(vertexCount * 3);
  const normals = new Float32Array(vertexCount * 3);
  const indices = new Uint32Array(indexCount);
  const faceRanges = new Uint32Array(chunks.length * 2);
  let vBase = 0;
  let iBase = 0;
  chunks.forEach((c, f) => {
    positions.set(c.positions, vBase * 3);
    normals.set(c.normals, vBase * 3);
    for (let i = 0; i < c.indices.length; i++) indices[iBase + i] = c.indices[i]! + vBase;
    faceRanges[f * 2] = iBase;
    faceRanges[f * 2 + 1] = c.indices.length;
    vBase += c.positions.length / 3;
    iBase += c.indices.length;
  });
  return { positions, normals, indices, faceRanges };
}
