// @manufakture/io: file formats. STL and 3MF are read and written here in
// plain TypeScript; STEP geometry goes through the kernel (OCCT's
// translators), and this package only reads STEP text (product names). 2D
// sheets (drawings, and laser and plasma outlines) are written as SVG, DXF and PDF,
// and SVG artwork is read as lines and arcs for sketches. Buildings are written as
// IFC through web-ifc, which is imported only when an IFC export runs (`./ifc`).
// A published view (`.mfkview`: meshes, names and metadata in a zip) is written with
// three's GLTFExporter, imported only when one is written, and read without three.

export const packageName = '@manufakture/io';

export {
  DEFAULT_WELD_TOLERANCE,
  meshProperties,
  mergeMeshes,
  weld,
  type MeshProperties,
  type NamedMesh,
  type TriMesh,
  type TriangleSoup,
  type Vec3,
  type WeldOptions,
} from './mesh';
export { checkManifold, type ManifoldOptions, type ManifoldReport } from './manifold';
export {
  StlParseError,
  parseStl,
  writeBinaryStl,
  type ParsedStl,
  type StlWriteOptions,
} from './stl';
export {
  CORE_NAMESPACE,
  MATERIALS_NAMESPACE,
  MODEL_PATH,
  MODEL_SETTINGS_PATH,
  ThreeMfParseError,
  buildMeshes,
  parse3mf,
  validate3mf,
  write3mf,
  type ModelUnit,
  type ParsedThreeMf,
  type ThreeMfBuildItem,
  type ThreeMfBuiltMesh,
  type ThreeMfColorGroup,
  type ThreeMfComponent,
  type ThreeMfComponentsInput,
  type ThreeMfItem,
  type ThreeMfMeshInput,
  type ThreeMfObject,
  type ThreeMfObjectInput,
  type ThreeMfReport,
  type ThreeMfSettingsObject,
  type ThreeMfWriteOptions,
} from './threemf';
export {
  IDENTITY_MATRIX,
  composeMatrices,
  matrixDeterminant,
  placementMatrix,
  transformMesh,
  type Matrix3x4,
  type Placement,
} from './placement';
export { decodeStepString, isStep, sniffFormat, stepProductNames, type FileFormat } from './step';
export {
  formatBytes,
  fromBase64,
  importSource,
  sha256Hex,
  toBase64,
  type ImportSourceData,
} from './encoding';
export {
  DEFAULT_EXPORT_TOLERANCE,
  EXPORT_TOLERANCES,
  NotWatertightError,
  deflectionOf,
  export3mf,
  export3mfAssembly,
  exportMesh,
  exportStl,
  exportStlAssembly,
  fileName,
  type ExportAssembly,
  type ExportBody,
  type ExportTolerance,
  type ExportTolerancePreset,
  type StlFile,
} from './export';
export {
  JOIN_TOLERANCE,
  LOOP_SNAP_TOLERANCE,
  baselinePoint,
  connectedRuns,
  formatNumber,
  isFullTurn,
  itemsByLayer,
  line,
  loopsToSheet,
  pageOf,
  polylinePath,
  segmentBeziers,
  segmentBounds,
  segmentPoint,
  sheetBounds,
  signedSweep,
  type Bounds2,
  type Item2,
  type Layer2,
  type Loop2,
  type LoopArc2,
  type LoopLayer2,
  type LoopLine2,
  type LoopSegment2,
  type LoopSheetOptions,
  type Path2,
  type Segment2,
  type Sheet2,
  type Text2,
  type TextAnchor,
  type TextBaseline,
  type Vec2 as Point2,
} from './path2';
export {
  LOOP_MAX_ARC_SWEEP,
  SVG_FONT_FAMILY,
  escapeXml,
  layerId,
  loopsToSvg,
  pathData,
  writeSvg,
  type SvgWriteOptions,
} from './svg';
export {
  DXF_LINEWEIGHTS,
  LOOP_BULGE_DIGITS,
  dxfColor,
  dxfLineweight,
  dxfName,
  dxfText,
  loopsToDxf,
  writeDxf,
  type DxfWriteOptions,
} from './dxf';
export { POINTS_PER_MM, contentStream, pdfTextString, writePdf, type PdfWriteOptions } from './pdf';
export { FABRICATION_MIME, documentFileName, type FabricationFile } from './fabrication';
export {
  ExportRefusedError,
  UNKNOWN_EXPORT_SOURCE,
  UNREVIEWED_EXPORT,
  assertExportAllowed,
  exportAllowed,
  type ExportSource,
  type ExportVerdict,
} from './export-gate';
export {
  exportBodyFiles,
  kernelExchanger,
  type BodyExchanger,
  type BodyFileFormat,
  type BodyFileOptions,
  type BodyFiles,
  type ExchangeOutcome,
  type KernelExchangeBody,
  type MemberBodiesLike,
} from './body-files';
export {
  matrix3x4,
  memberExportBodies,
  type MemberExportSource,
  type MemberInstancesLike,
} from './member-export';
export { stepStrings, withStepDescription } from './step-header';
export {
  HELVETICA_CAP_HEIGHT,
  helveticaTextWidth,
  helveticaWidth,
  winAnsiBytes,
} from './helvetica';
export {
  DRAWING_LINETYPES,
  displayListToSheet,
  drawingToDxf,
  drawingToPdf,
  drawingToSvg,
  type DrawingSheetOptions,
} from './drawing-export';
export {
  DRAWING_MIME,
  drawingFile,
  drawingFileName,
  screenSvg,
  type DrawingFile,
  type DrawingFormat,
} from './drawing-files';
export {
  DEFAULT_SVG_OUTLINE_TOLERANCE,
  DEFAULT_SVG_TOLERANCE,
  MAX_SVG_CHARS,
  MAX_SVG_COMMANDS,
  MAX_SVG_DEPTH,
  MAX_SVG_ELEMENTS,
  MAX_SVG_SEGMENTS,
  MAX_SVG_VISITS,
  SvgImportError,
  fitSvg,
  importSvg,
  parseLength,
  parsePathData,
  parseSvg,
  parseTransform,
  parseXml,
  placeSvgImport,
  svgAnchorPoint,
  svgGeometryBounds,
  svgImportCounts,
  svgOutlinePaths,
  type ParsedSvg,
  type SvgAnchor,
  type SvgBounds,
  type SvgCircle,
  type SvgContour,
  type SvgFillRule,
  type SvgFitOptions,
  type SvgImport,
  type SvgImportErrorCode,
  type SvgImportOptions,
  type SvgIssue,
  type SvgIssueCode,
  type SvgMatrix,
  type SvgOutlineCommand,
  type SvgOutlineLimit,
  type SvgOutlineOptions,
  type SvgOutlinePath,
  type SvgOutlinePaths,
  type SvgPathCommand,
  type SvgSegment,
  type SvgShape,
  type XmlElement,
} from './svg-import';
export {
  MFKVIEW_EXTENSION,
  MFKVIEW_FORMAT,
  MFKVIEW_LIMITS,
  MFKVIEW_MANIFEST,
  MFKVIEW_MIME,
  MFKVIEW_SOURCE,
  MFKVIEW_VERSION,
  MFKVIEW_VIEWER_LIMITS,
  MfkviewError,
  isRigidMatrix,
  mfkviewBodyEntry,
  parseMfkviewManifest,
  readMfkview,
  writeMfkview,
  type Mfkview,
  type MfkviewBodyInfo,
  type MfkviewInput,
  type MfkviewInstance,
  type MfkviewLimits,
  type MfkviewManifest,
  type MfkviewMaterial,
  type MfkviewMesh,
  type MfkviewPart,
} from './mfkview';
export { ZipReadError, formatByteCount, readZip, type ZipReadLimits, type ZipWanted } from './zip';
export {
  IFC_GUID_ALPHABET,
  IFC_GUID_PATTERN,
  IFC_SCHEMA,
  IFC_UNIT_MM,
  IFC_VIEW_DEFINITION,
  IfcExportError,
  MAX_IFC_COORDINATE,
  MAX_IFC_WORK,
  MAX_IFC_FLOORS,
  MAX_IFC_HEADER_STRING,
  MAX_IFC_HEADER_STRINGS,
  MAX_IFC_ID,
  MAX_IFC_LABEL,
  MAX_IFC_LAYERS,
  MAX_IFC_LEVELS,
  MAX_IFC_MEMBERS,
  MAX_IFC_OPENINGS,
  MAX_IFC_OPENINGS_PER_SEGMENT,
  MAX_IFC_OUTLINE_POINTS,
  MAX_IFC_ROOFS,
  MAX_IFC_SHEETS,
  MAX_IFC_SIZE,
  MAX_IFC_TEXT,
  MAX_IFC_WALL_POINTS,
  MAX_IFC_WALLS,
  checkIfcBuilding,
  compressGuid,
  expandGuid,
  faceRects,
  ifcGlobalId,
  ifcHeaderStrings,
  ifcString,
  loadWebIfc,
  memberClass,
  writeIfc,
  type IfcBuildingInput,
  type IfcFloorInput,
  type IfcLengthUnit,
  type IfcLevelInput,
  type IfcMemberInput,
  type IfcOpeningInput,
  type IfcPlaneInput,
  type IfcRoofInput,
  type IfcRoofKind,
  type IfcSheetInput,
  type IfcVec2,
  type IfcVec3,
  type IfcWallInput,
  type IfcWallLayerInput,
  type IfcWriteOptions,
} from './ifc';
