// @manufakture/domain-construction: the construction domain (M6). Framing generators that turn
// walls, floors and roofs into member data, the member data shape and its ids, the document-level
// construction data (`domains.construction`: levels, wall, floor and roof types, framing settings,
// header rules) and its regen registration, and the "not an engineering tool" text. See README.md.

export const packageName = '@manufakture/domain-construction';

export { DISCLAIMER_SHORT } from './disclaimer';
export {
  add,
  cross,
  dot,
  placementMatrix,
  scale,
  sub,
  toLocal,
  toWorld,
  zAxis,
  type Placement,
  type Plane,
  type Vec2,
  type Vec3,
} from './geom';
export {
  countByRole,
  memberCorners,
  shapeKey,
  type Cut,
  type Member,
  type Role,
  type StockRef,
} from './members';
export {
  formatOpeningMemberId,
  formatWallMemberId,
  memberFullId,
  memberIds,
  parseOpeningMemberId,
  parseWallMemberId,
  splitMemberFullId,
  type CornerMemberName,
  type OpeningMemberId,
  type TeeMemberName,
  type WallMemberId,
} from './member-ids';
export {
  DEFAULT_WALL_SETTINGS,
  FramingInputError,
  frameWall,
  resolveWallSettings,
  type BlockingRows,
  type CornerStyle,
  type FrameWallInput,
  type FramingWarning,
  type HeaderRule,
  type HeaderSpec,
  type Justification,
  type MemberOverride,
  type OpeningReport,
  type OverrideReport,
  type WallFraming,
  type WallJoin,
  type WallOpening,
  type WallSegment,
  type WallSettings,
  type WallSettingsInput,
  type WallTee,
  type WallWarningCode,
} from './framing/wall';
export {
  DEFAULT_FLOOR_SETTINGS,
  formatFloorMemberId,
  frameFloor,
  parseFloorMemberId,
  resolveFloorSettings,
  type FloorBlocking,
  type FloorFraming,
  type FloorMemberId,
  type FloorSettings,
  type FloorSettingsInput,
  type FloorWall,
  type FloorWarning,
  type FloorWarningCode,
  type FrameFloorInput,
  type SkidSettings,
  type SubfloorReport,
} from './framing/floor';
export {
  DEFAULT_ROOF_SETTINGS,
  formatRoofMemberId,
  frameRoof,
  parseRoofMemberId,
  resolveRoofSettings,
  type FrameRoofInput,
  type GableStuds,
  type RoofCorner,
  type RoofEdge,
  type RoofFootprint,
  type RoofFraming,
  type RoofGeometry,
  type RoofKind,
  type RoofMemberId,
  type RoofSettings,
  type RoofSettingsInput,
  type RoofTies,
  type RoofWarning,
  type RoofWarningCode,
  type TailCut,
} from './framing/roof';
export {
  CONSTRUCTION_DATA,
  CONSTRUCTION_DATA_VERSION,
  CONSTRUCTION_NAMESPACE,
  EMPTY_CONSTRUCTION_DATA,
  EMPTY_CONSTRUCTION_SETTINGS,
  LAYER_KINDS,
  MAX_HEADER_RULES,
  MAX_LAYERS,
  MAX_LENGTHS,
  MAX_TYPES,
  defaultConstructionSettings,
  layerThickness,
  mapLengths,
  newWallType,
  readConstructionData,
  wallTypeThickness,
  writeConstructionData,
  type BlockingRowsData,
  type ConstructionData,
  type ConstructionSettings,
  type FloorType,
  type FramingLayer,
  type FramingSettings,
  type HeaderData,
  type HeaderRuleData,
  type LayerKind,
  type NewWallTypeInput,
  type RoofType,
  type SheetLayer,
  type StoredConstructionSettings,
  type WallLayer,
  type WallType,
} from './data';
export {
  DATA_ID_PATTERN,
  MAX_LEVELS,
  findLevel,
  readLevels,
  type Level,
  type StoredLevel,
} from './levels';
export {
  CONSTRUCTION_STOCK,
  PRECUT_STUD_IDS,
  stockKind,
  stockRef,
  stockThickness,
  stockWidth,
} from './stock';
export { CONSTRUCTION_IMPLEMENTATION, constructionDomain, registerConstruction } from './domain';
