// @manufakture/domain-construction: the construction domain (M6). Framing generators that turn
// walls, floors and roofs into member data, the member data shape and its ids, the document-level
// construction data (`domains.construction`: levels, wall, floor and roof types, framing settings,
// header rules) and its regen registration, and the "not an engineering tool" text. See README.md.

export const packageName = '@manufakture/domain-construction';

export { DISCLAIMER_SHORT } from './disclaimer';
export {
  add,
  cross,
  dot,
  placementMatrix,
  scale,
  sub,
  toLocal,
  toWorld,
  zAxis,
  type Placement,
  type Plane,
  type Vec2,
  type Vec3,
} from './geom';
export {
  MEMBER_BUDGET,
  countByRole,
  memberCorners,
  shapeKey,
  type Cut,
  type Member,
  type Role,
  type StockRef,
} from './members';
export {
  formatOpeningMemberId,
  formatWallMemberId,
  memberFullId,
  memberIds,
  parseOpeningMemberId,
  parseWallMemberId,
  splitMemberFullId,
  type CornerMemberName,
  type OpeningMemberId,
  type TeeMemberName,
  type WallMemberId,
} from './member-ids';
export {
  DEFAULT_WALL_SETTINGS,
  FramingInputError,
  MemberBudget,
  frameWall,
  resolveWallSettings,
  type BlockingRows,
  type CornerStyle,
  type FrameWallInput,
  type FramingWarning,
  type HeaderRule,
  type HeaderSpec,
  type Justification,
  type MemberOverride,
  type OpeningReport,
  type OverrideReport,
  type WallFraming,
  type WallJoin,
  type WallOpening,
  type WallSegment,
  type WallSettings,
  type WallSettingsInput,
  type WallTee,
  type WallWarningCode,
} from './framing/wall';
export {
  DEFAULT_FLOOR_SETTINGS,
  formatFloorMemberId,
  frameFloor,
  parseFloorMemberId,
  resolveFloorSettings,
  type FloorBlocking,
  type FloorFraming,
  type FloorMemberId,
  type FloorSettings,
  type FloorSettingsInput,
  type FloorWall,
  type FloorWarning,
  type FloorWarningCode,
  type FrameFloorInput,
  type SkidSettings,
  type SubfloorReport,
} from './framing/floor';
export {
  DEFAULT_ROOF_SETTINGS,
  formatRoofMemberId,
  frameRoof,
  parseRoofMemberId,
  resolveRoofSettings,
  type FrameRoofInput,
  type GableStuds,
  type RoofCorner,
  type RoofEdge,
  type RoofFootprint,
  type RoofFraming,
  type RoofGeometry,
  type RoofKind,
  type RoofMemberId,
  type RoofSettings,
  type RoofSettingsInput,
  type RoofTies,
  type RoofWarning,
  type RoofWarningCode,
  type TailCut,
} from './framing/roof';
export {
  CONSTRUCTION_DATA,
  CONSTRUCTION_DATA_VERSION,
  CONSTRUCTION_NAMESPACE,
  EMPTY_CONSTRUCTION_DATA,
  EMPTY_CONSTRUCTION_SETTINGS,
  LAYER_KINDS,
  MAX_HEADER_RULES,
  MAX_LAYERS,
  MAX_LENGTHS,
  MAX_SETTING_LENGTH,
  MAX_TAKEOFF_STOCKS,
  MAX_TYPES,
  MAX_WASTE_PERCENT,
  MIN_PLATE_STOCK,
  MIN_SPACING,
  defaultConstructionSettings,
  documentConstruction,
  layerThickness,
  mapLengths,
  newWallType,
  readConstructionData,
  wallTypeThickness,
  writeConstructionData,
  type BlockingRowsData,
  type ConstructionData,
  type ConstructionSettings,
  type FloorType,
  type FramingLayer,
  type FramingSettings,
  type HeaderData,
  type HeaderRuleData,
  type TakeoffSettingsData,
  type LayerKind,
  type NewWallTypeInput,
  type RoofType,
  type SheetLayer,
  type StoredConstructionSettings,
  type WallLayer,
  type WallType,
} from './data';
export {
  DATA_ID_PATTERN,
  MAX_LEVEL_LENGTH,
  MAX_LEVELS,
  findLevel,
  readLevels,
  type Level,
  type StoredLevel,
} from './levels';
export {
  CONSTRUCTION_STOCK,
  PRECUT_STUD_IDS,
  stockKind,
  stockRef,
  stockThickness,
  stockWidth,
} from './stock';
export {
  CONSTRUCTION_IMPLEMENTATION,
  constructionDomain,
  constructionMembers,
  registerConstruction,
} from './domain';
export {
  MAX_COORDINATE,
  MAX_OVERRIDES,
  MAX_SEGMENT_LENGTH,
  MAX_WALL_HEIGHT,
  MAX_WALL_POINTS,
  OPENING_TYPE,
  WALL_TYPE,
  moveExpression,
  readOpeningMetadata,
  readWallMetadata,
  type LayerMetadata,
  type OpeningHeader,
  type OpeningMetadata,
  type StoredOverride,
  type WallMetadata,
} from './features/common';
export {
  WALL_EXPRESSIONS,
  WALL_PARAMS,
  WALL_SCHEMA_VERSION,
  layerArea,
  layerBodyId,
  layerLoops,
  readWallParams,
  translateWall,
  wallLayerBodies,
  wallType,
  type WallEndJoin,
  type WallFramingParams,
  type WallParams,
} from './features/wall';
export {
  OPENING_EXPRESSIONS,
  OPENING_PARAMS,
  OPENING_SCHEMA_VERSION,
  openingScope,
  openingType,
  readOpeningParams,
  translateOpening,
  type OpeningKind,
  type OpeningParams,
  type StoredOpeningHeader,
} from './features/opening';
export {
  MAX_GRAPH_SEGMENTS,
  framedWall,
  wallGraph,
  type GraphWall,
  type WallGraph,
} from './features/graph';
export { MAX_LAYER_JOIN_WALLS } from './features/graph';
export {
  FLOOR_EXPRESSIONS,
  FLOOR_PARAMS,
  FLOOR_SCHEMA_VERSION,
  FLOOR_TYPE,
  MAX_FLOOR_JOISTS,
  MAX_FLOOR_SLOTS,
  MAX_FLOOR_WALLS,
  MAX_FLOOR_WALL_SEGMENTS,
  MAX_OUTLINE_POINTS,
  MAX_SKIDS,
  exteriorRing,
  floorGroups,
  floorType,
  frameFloorGroup,
  readFloorMetadata,
  readFloorParams,
  translateFloor,
  type FloorMetadata,
  type FloorOutlineSource,
  type FloorParams,
  type RingEdge,
  type WallRing,
} from './features/floor';
export {
  MAX_OVERHANG,
  MAX_PITCH,
  MAX_TIE_EVERY,
  ROOF_EXPRESSIONS,
  ROOF_PARAMS,
  ROOF_SCHEMA_VERSION,
  ROOF_TYPE,
  frameRoofGroup,
  readRoofMetadata,
  readRoofParams,
  roofGroups,
  roofType,
  sheathingArea,
  sheathingOutlines,
  translateRoof,
  type RoofMetadata,
  type RoofParams,
  type RoofTiesParams,
} from './features/roof';
export {
  readViewParams,
  VIEW_PARAMS_VERSION,
  type ConstructionViewParams,
  type OpeningStops,
} from './drawings/params';
export { cornerRange, memberOutline, memberSection, type Segment3 } from './drawings/outline';
export {
  CHAIN_OFFSET,
  DEFAULT_PLAN_CUT,
  MAX_VIEW_LINES,
  constructionDrawings,
  constructionView,
} from './drawings/views';
export {
  constructionGroups,
  constructionMemberStage,
  frameConstructionGroup,
  type WallGroupMetadata,
} from './features/stage';
export {
  CONSTRUCTION_CATEGORIES,
  DEFAULT_TAKEOFF_SETTINGS,
  LAYER_LABELS,
  LINEAR_GROUPS,
  PRECUT_ROLES,
  ROLE_LABELS,
  SPLICE_ROLES,
  constructionTakeoff,
  faceArea,
  layoutFace,
  precutFor,
  roofSheathingFaces,
  subfloorFace,
  wallFace,
  type ConstructionCategory,
  type ConstructionFlag,
  type ConstructionRow,
  type ConstructionTakeoff,
  type ConstructionTakeoffInput,
  type ConstructionTakeoffSettings,
  type CostSummary,
  type FaceLayout,
  type FaceOpening,
  type FacePiece,
  type FaceRect,
  type LumberStockLayout,
  type SheetFace,
  type SheetLayerKind,
  type SheetStockLayout,
  type TakeoffMember,
  type TakeoffSubtotal,
  type WallFaceInput,
} from './takeoff';
export * from './ifc/adapter';
export {
  SECTIONS,
  costLines,
  displayRows,
  flagText,
  money,
  sections,
  stockName,
  subtotalLines,
  takeoffCsv,
  totalsText,
  type TakeoffCsvOptions,
  type TakeoffDisplayRow,
} from './takeoff/display';
export {
  faceSpans,
  takeoffModel,
  takeoffSettings,
  type TakeoffMemberSet,
  type TakeoffModel,
  type TakeoffSources,
} from './takeoff/from-regen';
