// The browser half: each input document regenerated by the app's own regen worker
// (apps/web/src/viewport/regen-worker.ts through its spawner, so the same kernel build, solver,
// domains and text worker the app runs), one fresh worker per document so the regen is complete,
// then summarized exactly as Node summarizes it (../summary.ts). The inputs are the serialized
// documents Node wrote; the reply goes on `window.__result` for Playwright.

import { parseDocument } from '../../../../packages/core/src/index';
import { spawnAppRegenWorker } from '../../../../apps/web/src/viewport/regen-spawn';
import { mathProbe } from '../mathprobe';
import { summarize, type BodyMeasureLike, type Summary } from '../summary';

interface Input {
  key: string;
  text: string;
}

interface Output {
  key: string;
  ok: boolean;
  error?: string;
  summary?: Summary;
  ms?: { workerReady: number; regenWall: number; regenEngine: number };
}

async function one(input: Input): Promise<Output> {
  const parsed = parseDocument(JSON.parse(input.text));
  if (!parsed.ok) return { key: input.key, ok: false, error: parsed.error.message };
  const t0 = performance.now();
  const client = spawnAppRegenWorker();
  try {
    await client.ready;
    const ready = performance.now() - t0;
    const t1 = performance.now();
    const result = await client.regen(parsed.value.document);
    const wall = performance.now() - t1;
    if (result === null) return { key: input.key, ok: false, error: 'superseded' };
    const measure = async (shape: number): Promise<BodyMeasureLike | null> => {
      const reply = await client.submit(
        [{ op: 'measure', shape: shape as never, targets: [], body: true }] as const,
        client.latestGeneration,
      );
      const r = reply?.results[0];
      if (!r?.ok) throw new Error(`measure failed: ${JSON.stringify(r)}`);
      return (r.value as { body: BodyMeasureLike | null }).body;
    };
    const summary = await summarize(result, measure);
    return {
      key: input.key,
      ok: true,
      summary,
      ms: { workerReady: ready, regenWall: wall, regenEngine: result.ms },
    };
  } catch (e) {
    return {
      key: input.key,
      ok: false,
      error: e instanceof Error ? `${e.message}\n${e.stack}` : String(e),
    };
  } finally {
    client.terminate();
  }
}

async function run(): Promise<void> {
  const inputs = (await (await fetch('/inputs.json')).json()) as Input[];
  const out: Output[] = [];
  for (const input of inputs) {
    console.log(`regenerating ${input.key}`);
    out.push(await one(input));
  }
  (window as unknown as { __result: unknown }).__result = {
    ok: true,
    userAgent: navigator.userAgent,
    isolated: crossOriginIsolated,
    secure: isSecureContext,
    math: mathProbe(),
    outputs: out,
  };
}

run().catch((e: unknown) => {
  (window as unknown as { __result: unknown }).__result = { ok: false, error: String(e) };
});
