// @manufakture/domain-wood: the woodworking domain (ADR 0013). The stock catalog, the board
// feature (`wood.board`), the joint feature (`wood.joint`) and the slide feature (`wood.slide`,
// drawer slides from the hardware catalog) with their translators, the document data the domain
// owns (`domains.wood`, `domains.stock`), and the cut list (the woodworking producer of
// `@manufakture/takeoff`). See README.md.

export const packageName = '@manufakture/domain-wood';

export {
  PS20_BOARD_THICKNESS,
  PS20_BOARD_WIDTH,
  PS20_DIMENSION_THICKNESS,
  PS20_DIMENSION_WIDTH,
  STOCK,
  defaultRegion,
  findStock,
  inchLabel,
  inches,
  stockByRegion,
  type BoardFeetBasis,
  type StockCategory,
  type StockEntry,
  type StockKind,
  type StockRegion,
  type StockSize,
} from './catalog';
export {
  BOARD_EXPRESSIONS,
  BOARD_PARAMS,
  BOARD_SCHEMA_VERSION,
  BOARD_TYPE,
  JUSTIFY,
  MAX_REGION_ENTITIES,
  boardType,
  readBoardMetadata,
  readBoardParams,
  translateBoard,
  type BoardFrame,
  type BoardMetadata,
  type BoardParams,
  type GrainSpec,
  type Justify,
  type PanelParams,
  type StickParams,
} from './board';
export {
  EMPTY_STOCK_DATA,
  MAX_STOCK_OVERRIDES,
  PRICE_UNITS,
  STOCK_DATA,
  STOCK_DATA_VERSION,
  STOCK_NAMESPACE,
  documentStock,
  readStockData,
  resolveStock,
  writeStockData,
  type Price,
  type PriceUnit,
  type ResolvedStock,
  type StockData,
  type StockOverride,
  type StoredStockOverride,
} from './stock-data';
export {
  DEFAULT_WOOD_SETTINGS,
  MAX_STAGES,
  WOOD_DATA,
  WOOD_DATA_VERSION,
  WOOD_NAMESPACE,
  readWoodData,
  woodSettings,
  writeWoodData,
  type GrainRule,
  type SheetTrimSettings,
  type StoredWoodSettings,
  type WoodData,
  type WoodSettings,
} from './wood-data';
export {
  expressionText,
  stockDataSummariser,
  woodDataSummariser,
  type DomainDataSummariser,
} from './review';
export {
  DADO_STOPS,
  DEFAULT_DOWEL,
  JOINT_EXPRESSIONS,
  JOINT_KINDS,
  JOINT_PARAMS,
  JOINT_SCHEMA_VERSION,
  JOINT_TYPE,
  KIND_EXPRESSIONS,
  MAX_FINGERS,
  MAX_HOLES,
  POCKET_JIG,
  POCKET_SCREWS,
  jointType,
  pocketScrew,
  readJointMetadata,
  readJointParams,
  translateJoint,
  type BoxJointParams,
  type DadoParams,
  type DadoStop,
  type DowelParams,
  type JointHardware,
  type JointKind,
  type JointMetadata,
  type JointParams,
  type JointWarning,
  type PocketParams,
  type RabbetParams,
  type TenonParams,
} from './joints';
export {
  MOUNT_EXPRESSIONS,
  SLIDE_EXPRESSIONS,
  SLIDE_FAMILIES,
  SLIDE_OPENS,
  SLIDE_PARAMS,
  SLIDE_SCHEMA_VERSION,
  SLIDE_TYPE,
  findSlideFamily,
  findSlideSize,
  readSlideMetadata,
  readSlideParams,
  slideType,
  translateSlide,
  type SideMountClearance,
  type SlideClearance,
  type SlideFamily,
  type SlideMetadata,
  type SlideOpens,
  type SlideParams,
  type SlideSize,
  type UndermountClearance,
} from './slides';
export {
  blankBoardFeet,
  cutList,
  cutListPart,
  stockName,
  type BlankBoardFeet,
  type CutList,
  type CutListBody,
  type CutListFeature,
  type CutListFlag,
  type CutListInput,
  type CutListInstance,
  type CutListPart,
  type CutListPartOptions,
  type CutListRow,
  type ExcludedBody,
  type LumberLayoutInput,
  type MissingItem,
  type OrientedSize,
  type PartResultLike,
  type SheetLayoutInput,
  type SheetLayoutPart,
} from './cutlist';
export {
  FLAG_TEXT,
  activeRow,
  bodiesToSize,
  bomCsv,
  cutListCsv,
  cutListInput,
  displayRows,
  documentCutList,
  documentSettings,
  exactFormat,
  excludedLines,
  flagText,
  groupRows,
  missingLines,
  shortItem,
  totalBoardFeet,
  totalLines,
  type CutListPartModel,
  type CutListSources,
  type DisplayRow,
  type SortKey,
} from './cutlist/display';
export { nestingJob, purchase, type Purchase } from './cutlist/layout';
export {
  runNesting,
  type JobProgress,
  type LayoutNote,
  type NestingJob,
  type NestingResult,
  type SheetJob,
  type StickJob,
} from './cutlist/nesting';
export { WOOD_IMPLEMENTATION, registerWood, woodDomain } from './domain';
export { currentVersion, migrate, type Json, type Migration, type Versioned } from './migrations';
export { constantLength, type Path, type Read } from './read';
