// @manufakture/regen: turns a core document into geometry, rebuilding only what changed.
// See README.md for the design (where it runs, caching, errors, cancellation).

export const packageName = '@manufakture/regen';

export {
  RegenEngine,
  type EngineStats,
  type AssemblyOptions,
  type InterferenceCheckOptions,
  type RegenEngineOptions,
  type RegenKernel,
  type RegenOptions,
} from './engine';
export {
  DEFAULT_KERNEL_BUILD,
  DEFAULT_SOLVER_BUILD,
  MemoryCache,
  REGEN_IMPLEMENTATION_VERSION,
  cacheKey,
  holdsShapes,
  type CacheEntry,
  type CachedBody,
  type CachedOutcome,
  type FeatureCache,
  type KeyVersions,
  type MemoryCacheOptions,
} from './cache';
export {
  ExtensionRegistry,
  defaultExtensions,
  extensionNamespace,
  type DomainDataReader,
  type ExpressionKind,
  type ExtensionContext,
  type ExtensionDomain,
  type ExtensionFailure,
  type ExtensionInputs,
  type ExtensionOutput,
  type ExtensionType,
  type ExtensionUpstream,
  type GeometryAnswer,
  type GeometryQuery,
  type JsonValue,
  type ReadResult,
  type RegisteredExtension,
  type ResolvedReference,
} from './extensions';
export {
  BODY_KINDS,
  bodyUse,
  buildGraph,
  changedDomains,
  changedVariables,
  dirtyFeatures,
  dirtyFeaturesOf,
  isBodyFeature,
  readsBody,
  regenOrder,
  routeBodies,
  sameInputs,
  topologicalOrder,
  variableClosure,
  type BodyUse,
  type DependencyGraph,
  type DirtyOptions,
  type RoutedBody,
} from './graph';
export {
  evaluateFeature,
  evaluateField,
  evaluateVariables,
  pathKey,
  type FeatureValues,
  type VariableValues,
} from './values';
export {
  MAX_SKETCH_OUTLINE_CURVES,
  expandOutlines,
  explicitPlacement,
  profileOf,
  selectRegions,
  sketchFontKey,
  sketchOutcome,
  solveSketch,
  type OutlineContext,
  type OutlineExpansion,
  type RegenSolver,
  type SketchResult,
  type SolveOutcome,
} from './sketches';
export {
  MAX_FONT_NAME_LENGTH,
  MAX_TEXT_CURVES,
  MAX_TEXT_LOOPS,
  MAX_TEXT_POINTS,
  TEXT_FONT_BUDGET_MS,
  TEXT_REGEN_BUDGET_MS,
  TEXT_TIME_LIMIT_MS,
  TextBudget,
  TextCancelled,
  createWatchdogOutliner,
  fontTooLarge,
  lazyTextOutliner,
  unreadableFont,
  type FontReadReply,
  type FontReader,
  type FontSummary,
  type TextCallOptions,
  type TextFontRef,
  type TextOutliner,
  type TextReply,
  type TextRequest,
  type WatchdogOutlinerOptions,
  type WireFont,
  type WireReply,
  type WireRequest,
} from './text';
export {
  TextEngine,
  createTextOutliner,
  fontSummary,
  serveText,
  textTooComplex,
  type TextEngineOptions,
  type TextOutlinerOptions,
} from './text-engine';
export { Watchdog, WatchdogError, type WatchdogOptions, type WorkerLike } from './watchdog';
export {
  edgeRef,
  faceRef,
  referenceIdOf,
  topoRef,
  translateFeature,
  type TranslateContext,
  type Translation,
} from './translate';
export {
  connectorOrigin,
  connectorPose,
  framePose,
  instanceSourceKey,
  posesDiffer,
} from './assembly';
export {
  DRAWING_STAGE_VERSION,
  DrawingStage,
  PICK_TIE_TOLERANCE,
  dimensionInput,
  drawingOffset,
  evaluateScale,
  pickInView,
  placeDirection,
  placeGeometry,
  placePoint,
  refTarget,
  sheetInput,
  titleBlockInput,
  valueFormat,
  viewDirection,
  type DimensionResult,
  type DimensionWarning,
  type DrawingBody,
  type DrawingDiagnostic,
  type DrawingHost,
  type DrawingItem,
  type DrawingRequestOptions,
  type DrawingSheetResult,
  type DrawingStats,
  type DrawingViewResult,
  type PickCylinder,
  type PickEdge,
  type PickHit,
  type PickItem,
  type PickKind,
  type PickOptions,
  type PickVertex,
  type RefGeometry,
  type ViewPickData,
} from './drawing';
export {
  directionInference,
  explodeTrails,
  explodeWarnings,
  explodedOffsets,
  explodedPose,
  resolveExplodedView,
  stepFraction,
  stepMove,
  type ExplodeContext,
  type ExplodeStepResult,
  type ExplodeTrail,
  type ExplodeWarning,
  type ExplodedViewResult,
} from './explode';
export { mapFailure, mapKernelError, mapKernelWarning, mapOutcome } from './errors';
export {
  ORIENTED_CACHE_SIZE,
  OrientedCache,
  type OrientedBodySize,
  type OrientedSizesOptions,
  type OrientedSizesResult,
  type OrientedStats,
} from './oriented';
export {
  CAM_LOOP_DEFLECTION,
  CAM_MESH_DEFLECTION,
  CAM_PARALLEL_TOLERANCE,
  CAM_STAGE_VERSION,
  CamStage,
  camTransferables,
  type CamBody,
  type CamBox,
  type CamDepthRange,
  type CamDrillPoint,
  type CamEntryValues,
  type CamFeedValues,
  type CamGeometryOptions,
  type CamGeometryResult,
  type CamHost,
  type CamLeadValues,
  type CamLoop,
  type CamMesh,
  type CamOperationResult,
  type CamOperationValues,
  type CamPartBuild,
  type CamPlanarLoops,
  type CamReference,
  type CamSegment,
  type CamSetupValues,
  type CamSourceResult,
  type CamSourceTag,
  type CamStageError,
  type CamStageErrorCode,
  type CamStageSizes,
  type CamStageWarning,
  type CamStageWarningCode,
  type CamStats,
  type CamToolValues,
  type CamUpAxis,
  type CamWcsUp,
} from './cam';
export { hashString, hashValue, stableStringify } from './hash';
export { regenTransferables } from './transfer';
export {
  createRegenWorkerApi,
  type RegenWorkerApi,
  type RegenWorkerApiOptions,
  type TextPreviewOptions,
} from './worker-api';
export type * from './types';
