// @manufakture/regen: turns a core document into geometry, rebuilding only what changed.
// See README.md for the design (where it runs, caching, errors, cancellation).

export const packageName = '@manufakture/regen';

export {
  RegenEngine,
  type EngineStats,
  type AssemblyOptions,
  type MemberBodiesOptions,
  type MemberStats,
  type InterferenceCheckOptions,
  type RegenEngineOptions,
  type RegenKernel,
  type RegenOptions,
} from './engine';
export {
  MAX_COORDINATE,
  MAX_HANDLES_PER_CALL,
  MAX_SKETCH_ENTITIES,
  MAX_SKETCH_LOOPS,
  SCRIPT_APIS,
  SCRIPT_API_V1_SURFACE,
  SCRIPT_LOCAL_ID_PATTERN,
  ScriptRun,
  type ScriptRunOutcome,
} from './script-api';
export {
  DENY_ALL_SCRIPTS,
  MAX_POLICY_ENTRIES,
  ScriptHost,
  checkScriptPolicy,
  scriptAllowed,
  scriptsNotRunError,
  sourceSha256,
  type ScriptOptions,
  type ScriptPolicy,
  type ScriptRunEvent,
  type ScriptStats,
} from './scripted';
export {
  DEFAULT_KERNEL_BUILD,
  DEFAULT_SOLVER_BUILD,
  MemoryCache,
  REGEN_IMPLEMENTATION_VERSION,
  cacheKey,
  holdsShapes,
  type CacheEntry,
  type CachedBody,
  type CachedOutcome,
  type FeatureCache,
  type KeyVersions,
  type MemoryCacheOptions,
} from './cache';
export {
  ExtensionRegistry,
  defaultExtensions,
  extensionNamespace,
  type DomainDataReader,
  type ExpressionKind,
  type ExtensionContext,
  type ExtensionDomain,
  type ExtensionFailure,
  type ExtensionInputs,
  type ExtensionOutput,
  type ExtensionType,
  type ExtensionUpstream,
  type GeometryAnswer,
  type GeometryQuery,
  type JsonValue,
  type ParamIdField,
  type ReadResult,
  type RegisteredDomainDrawings,
  type RegisteredExtension,
  type RegisteredMemberStage,
  type ResolvedReference,
} from './extensions';
export {
  DOMAIN_VIEW_LAYERS,
  MAX_CHAIN_OFFSET,
  MAX_DOMAIN_CHAIN_MARKS,
  MAX_DOMAIN_CHAIN_POINTS,
  MAX_DOMAIN_TITLE_NOTE_LENGTH,
  MAX_DOMAIN_VIEW_ARCS,
  MAX_DOMAIN_VIEW_BODIES,
  MAX_DOMAIN_VIEW_CHAIN_ITEMS,
  MAX_DOMAIN_VIEW_CHAINS,
  MAX_DOMAIN_VIEW_LINES,
  MAX_DOMAIN_VIEW_SYMBOLS,
  MAX_DOMAIN_VIEW_WARNINGS,
  MAX_REQUEST_DOMAIN_ITEMS,
  checkDomainView,
  domainViewCost,
  type DomainArc,
  type DomainChain,
  type DomainDrawings,
  type DomainLine,
  type DomainPitch,
  type DomainVec3,
  type DomainViewContext,
  type DomainViewLayer,
  type DomainViewOutput,
  type DomainViewSet,
  type ExpressionResult,
} from './domain-views';
export {
  MAX_GROUP_MEMBERS,
  MAX_MEMBER_CUTS,
  MAX_MEMBER_SIZE,
  MEMBER_STAGE_VERSION,
  boxMesh,
  loadManifold,
  memberFullId,
  memberInstances,
  memberShapeKey,
  meshVolume,
  type ManifoldLoader,
  type MemberCut,
  type MemberData,
  type MemberFeature,
  type MemberGroup,
  type MemberGroupContext,
  type MemberInstances,
  type MemberMesh,
  type MemberMeshData,
  type MemberMeshUpdate,
  type MemberOutput,
  type MemberPlacement,
  type MemberPlane,
  type MemberSetResult,
  type MemberStage,
  type MemberStageContext,
  type MemberStock,
  type MemberVec3,
  type MemberWarning,
} from './members';
export {
  BODY_KINDS,
  bodyUse,
  buildGraph,
  changedDomains,
  changedVariables,
  dirtyFeatures,
  dirtyFeaturesOf,
  isBodyFeature,
  readsBody,
  regenOrder,
  routeBodies,
  sameInputs,
  topologicalOrder,
  variableClosure,
  type BodyUse,
  type DependencyGraph,
  type DirtyOptions,
  type RoutedBody,
} from './graph';
export {
  evaluateFeature,
  evaluateField,
  evaluateVariables,
  pathKey,
  type FeatureValues,
  type VariableValues,
} from './values';
export {
  MAX_SKETCH_OUTLINE_CURVES,
  expandOutlines,
  explicitPlacement,
  profileOf,
  selectRegions,
  sketchFontKey,
  sketchOutcome,
  solveSketch,
  type OutlineContext,
  type OutlineExpansion,
  type RegenSolver,
  type SketchResult,
  type SolveOutcome,
} from './sketches';
export {
  MAX_FONT_NAME_LENGTH,
  MAX_TEXT_CURVES,
  MAX_TEXT_LOOPS,
  MAX_TEXT_POINTS,
  TEXT_FONT_BUDGET_MS,
  TEXT_REGEN_BUDGET_MS,
  TEXT_TIME_LIMIT_MS,
  TextBudget,
  TextCancelled,
  createWatchdogOutliner,
  fontTooLarge,
  lazyTextOutliner,
  unreadableFont,
  type FontReadReply,
  type FontReader,
  type FontSummary,
  type TextCallOptions,
  type TextFontRef,
  type TextOutliner,
  type TextReply,
  type TextRequest,
  type WatchdogOutlinerOptions,
  type WireFont,
  type WireReply,
  type WireRequest,
} from './text';
export {
  TextEngine,
  createTextOutliner,
  fontSummary,
  serveText,
  textTooComplex,
  type TextEngineOptions,
  type TextOutlinerOptions,
} from './text-engine';
export { Watchdog, WatchdogError, type WatchdogOptions, type WorkerLike } from './watchdog';
export {
  edgeRef,
  faceRef,
  referenceIdOf,
  topoRef,
  translateFeature,
  type TranslateContext,
  type Translation,
} from './translate';
export {
  connectorFrames,
  connectorOrigin,
  connectorPose,
  framePose,
  instanceSourceKey,
  limitWarning,
  MAX_SWEEP_VALUES,
  namedCoordinates,
  posedMates,
  posesDiffer,
  resultSolverInput,
  solvedPoses,
  sweepPoses,
  sweepValues,
  type ConnectorFrame,
  type NamedCoordinate,
  type PosedMateCheck,
  type SweepStep,
} from './assembly';
export {
  DRAWING_STAGE_VERSION,
  DrawingStage,
  PICK_TIE_TOLERANCE,
  dimensionInput,
  drawingOffset,
  evaluateScale,
  pickInView,
  placeDirection,
  placeGeometry,
  placePoint,
  refTarget,
  sheetInput,
  titleBlockInput,
  valueFormat,
  viewDirection,
  type DimensionResult,
  type DimensionWarning,
  type DrawingBody,
  type DrawingDiagnostic,
  type DrawingHost,
  type DrawingItem,
  type DrawingRequestOptions,
  type DrawingSheetResult,
  type DrawingStats,
  type DrawingViewResult,
  type PickCylinder,
  type PickEdge,
  type PickHit,
  type PickItem,
  type PickKind,
  type PickOptions,
  type PickVertex,
  type RefGeometry,
  type ViewPickData,
} from './drawing';
export {
  directionInference,
  explodeTrails,
  explodeWarnings,
  explodedOffsets,
  explodedPose,
  resolveExplodedView,
  stepFraction,
  stepMove,
  type ExplodeContext,
  type ExplodeStepResult,
  type ExplodeTrail,
  type ExplodeWarning,
  type ExplodedViewResult,
} from './explode';
export { mapFailure, mapKernelError, mapKernelWarning, mapOutcome } from './errors';
export {
  ORIENTED_CACHE_SIZE,
  OrientedCache,
  type OrientedBodySize,
  type OrientedSizesOptions,
  type OrientedSizesResult,
  type OrientedStats,
} from './oriented';
export {
  CAM_DRILL_MAX_PECKS,
  CAM_LOOP_DEFLECTION,
  CAM_MAX_TABS,
  CAM_MESH_DEFLECTION,
  CAM_MIN_ENTRY_ANGLE,
  CAM_MIN_TOOL_DIAMETER,
  CAM_PARALLEL_TOLERANCE,
  CAM_STAGE_VERSION,
  CamStage,
  SURFACE3D_MIN_SAMPLING,
  camTransferables,
  type CamBody,
  type CamBox,
  type CamDepthRange,
  type CamDrillPoint,
  type CamEntryValues,
  type CamFeedValues,
  type CamGeometryOptions,
  type CamGeometryResult,
  type CamHost,
  type CamLeadValues,
  type CamLoop,
  type CamMesh,
  type CamOperationResult,
  type CamOperationValues,
  type CamPartBuild,
  type CamPlanarLoops,
  type CamReference,
  type CamSegment,
  type CamSetupValues,
  type CamSourceResult,
  type CamSourceTag,
  type CamStageError,
  type CamStageErrorCode,
  type CamStageSizes,
  type CamStageWarning,
  type CamStageWarningCode,
  type CamStats,
  type CamToolValues,
  type CamUpAxis,
  type CamWcsUp,
} from './cam';
export { hashString, hashValue, stableStringify } from './hash';
export { memberBodiesTransferables, regenTransferables } from './transfer';
export {
  createRegenWorkerApi,
  type RegenWorkerApi,
  type RegenWorkerApiOptions,
  type ScriptDeclarationSource,
  type ScriptDeclarationsReply,
  type TextPreviewOptions,
} from './worker-api';
export type * from './types';
